<section role="main" id="main">
    <section class="container">
        <section class="row featured-items">

            <div class="flash-messages">
                <div class="alert alert-warning text-center">
                    <p>Nie możesz korzystać z wybrane pakietu. Pakiet jest <strong><abbr title="Przejdź do zakładki Płatności aby w szybki sposób móc aktywować usługę.">Nieaktywny</abbr></strong>. Opłać pakiet by móc w pełni korzystać z funkcjonalności serwisu.</p>
                </div>
            </div>
            <div class="toolbar">
                <ol class="breadcrumb">
                    <li class="home"><a href="/"><i class="fa fa-home"></i><span> Home</span></a></li>
                    <li class="active"><a href="/user/login" class=" active">Firma</a></li>
                    <li class="active"><a href="/user/profile" class=" active">Ustawienia</a></li>
                </ol>
            </div>
            <div class="wrapper">
                <div class="primary">
                    <section class="module">
                        <div class="module-content dis-table col-lg-12">
                            <div class="col-lg-12">

                                        <div class="col-sm-12 col-md-12">
                                            <!-- Split button -->
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default">
                                                    <div class="checkbox" style="margin: 0;">
                                                        <label>
                                                            <input type="checkbox">
                                                        </label>
                                                    </div>
                                                </button>
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                                    <span class="caret"></span><span class="sr-only">Toggle Dropdown</span>
                                                </button>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="#">All</a></li>
                                                    <li><a href="#">None</a></li>
                                                    <li><a href="#">Read</a></li>
                                                    <li><a href="#">Unread</a></li>
                                                    <li><a href="#">Starred</a></li>
                                                    <li><a href="#">Unstarred</a></li>
                                                </ul>
                                            </div>
                                            <button type="button" class="btn btn-default" data-toggle="tooltip" title="Refresh">
                                                <span class="glyphicon glyphicon-refresh"></span>   </button>
                                            <!-- Single button -->
                                            <div class="btn-group">
                                                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                                                    More <span class="caret"></span>
                                                </button>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="#">Mark all as read</a></li>
                                                    <li class="divider"></li>
                                                    <li class="text-center"><small class="text-muted">Select messages to see more actions</small></li>
                                                </ul>
                                            </div>
                                            <div class="pull-right">
                                                <span class="text-muted"><b>1</b>–<b>50</b> of <b>277</b></span>
                                                <div class="btn-group btn-group-sm">
                                                    <button type="button" class="btn btn-default">
                                                        <span class="glyphicon glyphicon-chevron-left"></span>
                                                    </button>
                                                    <button type="button" class="btn btn-default">
                                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    <hr />
                                    <div class="row">
                                        <div class="col-sm-12 col-md-12">
                                            <!-- Nav tabs -->
                                            <ul class="nav nav-tabs">
                                                <li class="active"><a href="#home" data-toggle="tab"><span class="glyphicon glyphicon-inbox">
                </span>Primary</a></li>
                                                <li><a href="#profile" data-toggle="tab"><span class="glyphicon glyphicon-user"></span>
                                                        Social</a></li>
                                                <li><a href="#messages" data-toggle="tab"><span class="glyphicon glyphicon-tags"></span>
                                                        Promotions</a></li>
                                                <li><a href="#settings" data-toggle="tab"><span class="glyphicon glyphicon-plus no-margin">
                </span></a></li>
                                            </ul>
                                            <!-- Tab panes -->
                                            <div class="tab-content">
                                                <div class="tab-pane fade in active" id="home">
                                                    <div class="list-group">
                                                        <a href="#" class="list-group-item">
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input type="checkbox">
                                                                </label>
                                                            </div>
                                                            <span class="glyphicon glyphicon-star-empty"></span><span class="name" style="min-width: 120px;
                                display: inline-block;">Bhaumik Patel</span> <span class="">This is big title</span>
                                                            <span class="text-muted" style="font-size: 11px;">- Hi hello how r u ?</span> <span
                                                                class="badge">12:10 AM</span> <span class="pull-right"><span class="glyphicon glyphicon-paperclip">
                                </span></span></a><a href="#" class="list-group-item">
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input type="checkbox">
                                                                </label>
                                                            </div>
                                                            <span class="glyphicon glyphicon-star-empty"></span><span class="name" style="min-width: 120px;
                                        display: inline-block;">Bhaumik Patel</span> <span class="">This is big title</span>
                                                            <span class="text-muted" style="font-size: 11px;">- Hi hello how r u ?</span> <span
                                                                class="badge">12:10 AM</span> <span class="pull-right"><span class="glyphicon glyphicon-paperclip">
                                        </span></span></a><a href="#" class="list-group-item read">
                                                            <div class="checkbox">
                                                                <label>
                                                                    <input type="checkbox">
                                                                </label>
                                                            </div>
                                                            <span class="glyphicon glyphicon-star"></span><span class="name" style="min-width: 120px;
                                                display: inline-block;">Bhaumik Patel</span> <span class="">This is big title</span>
                                                            <span class="text-muted" style="font-size: 11px;">- Hi hello how r u ?</span> <span
                                                                class="badge">12:10 AM</span> <span class="pull-right"><span class="glyphicon glyphicon-paperclip">
                                                </span></span></a>
                                                    </div>
                                                </div>
                                                <div class="tab-pane fade in" id="profile">
                                                    <div class="list-group">
                                                        <div class="list-group-item">
                                                            <span class="text-center">This tab is empty.</span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="tab-pane fade in" id="messages">
                                                    ...</div>
                                                <div class="tab-pane fade in" id="settings">
                                                    This tab is empty.</div>
                                            </div>
                                        </div>

                            </div>
                        </div>
                    </section>
                </div>
                <aside class="secondary">
                    <section class="module module-narrow module-shallow">
                        <?= $this->partial('company/company/partial/settings.phtml', array(
                            'action' => $this->action,
                            'method' => $this->method
                        )); ?>
                    </section>
                </aside>
            </div>
        </section>
    </section>
</section>