<section role="main" id="main">
    <section class="container">
        <section class="row featured-items">

            <div class="flash-messages">
                <div class="alert alert-warning text-center">
                    <p>Nie możesz korzystać z wybrane pakietu. Pakiet jest <strong><abbr title="Przejdź do zakładki Płatności aby w szybki sposób móc aktywować usługę.">Nieaktywny</abbr></strong>. Opłać pakiet by móc w pełni korzystać z funkcjonalności serwisu.</p>
                </div>
            </div>
            <div class="toolbar">
                <ol class="breadcrumb">
                    <li class="home"><a href="/"><i class="fa fa-home"></i><span> Home</span></a></li>
                    <li class="active"><a href="/user/login" class=" active">Firma</a></li>
                    <li class="active"><a href="/user/profile" class=" active">Płatności</a></li>
                </ol>
            </div>
            <div class="wrapper">
                <div class="primary">
                    <section class="module">
                        <div class="module-content dashboard-profile dis-table col-lg-12">
                            <div class="col-lg-12">
                                <h3>Płatności</h3>

                                <div>
                                    <!--Przelewy24.pl - wybor formy platnosci-->
                                    <script src="https://secure.przelewy24.pl/external/formy.php?id=TWOJEID&sort=2" type="text/javascript"></script>
                                    <script type="text/javascript">m_formy();</script>
                                    <h2>Panel testowy do usługi Przelewy24</h2>
                                    <h2>Formularz żądania transakcji:</h2>
                                    <form method="post" class="form" id="fformn">
                                        <table class="serwer">
                                            <tr>
                                                <td>Serwer</td>
                                                <td>TrnRegister</td>
                                                <td>TrnDirect</td></tr>
                                            <tr>
                                                <td>Sandbox</td>
                                                <td><input type="radio" onclick="document.getElementById('fformn').action='client.php'" name="env" value="1" checked /></td>
                                                <td><input type="radio" onclick="document.getElementById('fformn').action='https://sandbox.przelewy24.pl/trnDirect'" name="env" value="2"  /></td>
                                            </tr>
                                            <tr>
                                                <td>Live</td>
                                                <td><input type="radio" onclick="document.getElementById('fformn').action='client.php'" name="env" value="2"  /></td>
                                                <td><input type="radio" onclick="document.getElementById('fformn').action='https://secure.przelewy24.pl/trnDirect'" name="env" value="4"  /></td>
                                            </tr>
                                        </table>
                                        <table>
                                            <tr><td>CRC_key</td><td><input type="text" style="width:250px" name="salt" value="" /></td></tr>
                                            <tr><td>Redirect</td><td><input type="checkbox" name="redirect" /><span>Zaznaczenie checkboxa powoduje automatyczne przekierowanie na stronê trnRequest.</span></td></tr>
                                            <tr><td>p24_merchant_id</td><td><input type="text" style="width:250px" name="p24_merchant_id" value="" /></td></tr>
                                            <tr><td>p24_pos_id</td><td><input type="text" style="width:250px" name="p24_pos_id" value="" /></td></tr>
                                            <tr><td>p24_session_id</td><td><input type="text" style="width:250px" name="p24_session_id" value="<?php echo md5(session_id().date("YmdHis")); ?>" /></td></tr>
                                            <tr><td>p24_amount</td><td><input type="text" style="width:250px" name="p24_amount" value="512" /></td></tr>
                                            <tr><td>p24_currency</td><td><input type="text" style="width:250px" name="p24_currency" value="PLN" /></td></tr>
                                            <tr><td>p24_description</td><td><input type="text" style="width:250px" name="p24_description" value="Zamówienie testowe" /></td></tr>
                                            <tr><td>p24_email</td><td><input type="text" style="width:250px" name="p24_email" value="no-reply@przelewy24.pl" /></td></tr>
                                            <tr><td>p24_client</td><td><input type="text" style="width:250px" name="p24_client" value="Jan Kowalski" /></td></tr>
                                            <tr><td>p24_address</td><td><input type="text" style="width:250px" name="p24_address" value="ul. Kwiatowa 13" /></td></tr>
                                            <tr><td>p24_zip</td><td><input type="text" style="width:250px" name="p24_zip" value="60-111" /></td></tr>
                                            <tr><td>p24_city</td><td><input type="text" style="width:250px" name="p24_city" value="Poznañ" /></td></tr>
                                            <tr><td>p24_country</td><td><input type="text" style="width:250px" name="p24_country" value="PL" /></td></tr>
                                            <tr><td>p24_phone*</td><td><input type="text" style="width:250px" name="p24_phone" value="611111111" /></td></tr>
                                            <tr><td>p24_language*</td><td><input type="text" style="width:250px" name="p24_language" value="PL" /></td></tr>
                                            <tr><td>p24_method*</td><td><input type="text" style="width:250px" name="p24_method" value="" /></td></tr>
                                            <tr><td>p24_url_return</td><td><input type="text" style="width:250px" name="p24_url_return" value="<?echo $this->protocol.$_SERVER['HTTP_HOST'].$_SERVER['SCRIPT_NAME']."?ok=1"?>" />Podaj adres w przypadku powrotu po zakoñczeniu transakcji. (http://nazwa_domeny/sample/client.php?ok=1)</td></tr>
                                            <tr><td>p24_url_status</td><td><input type="text" style="width:250px" name="p24_url_status" value="<?echo $this->protocol.$_SERVER['HTTP_HOST'].$_SERVER['SCRIPT_NAME']."?ok=2"?>" />Podaj adres skryptu weryfikuj±cego transakcjê.(http://nazwa_domeny/sample/client.php?ok=2)</td></tr>
                                            <tr><td>p24_time_limit*</td><td><input type="text" style="width:250px" name="p24_time_limit" value="29" /></td></tr>
                                            <tr><td>p24_wait_for_result*</td><td><input type="text" style="width:250px" name="p24_wait_for_result" value="1" /></td></tr>
                                            <tr><td>p24_ecod*</td><td><input type="text" style="width:250px" name="p24_ecod" value="" /></td></tr>
                                            <tr><td>p24_shipping*</td><td><input type="text" style="width:250px" name="p24_shipping" value="2500" /></td></tr>
                                            <tr><td>p24_name_1*</td><td><input type="text" style="width:250px" name="p24_name_1" value="Pizza" /></td></tr>
                                            <tr><td>p24_description_1*</td><td><input type="text" style="width:250px" name="p24_description_1" value="Smaczna, zdrowa..." /></td></tr>
                                            <tr><td>p24_quantity_1</td><td><input type="text" style="width:250px" name="p24_quantity_1" value="2" /></td></tr>
                                            <tr><td>p24_price_1*</td><td><input type="text" style="width:250px" name="p24_price_1" value="1250" /></td></tr>
                                            <tr><td>p24_number_1*</td><td><input type="text" style="width:250px" name="p24_number_1" value="1367" /></td></tr>
                                            <tr><td>p24_transfer_label*</td><td><input type="text" style="width:250px" name="p24_transfer_label" value="MyStore" /></td></tr>
                                            <tr><td>p24_api_version</td><td><input type="text" style="width:250px" name="p24_api_version" value="<?php echo $this->version; ?>" /></td></tr>
                                        </table>
                                        <input name="submit_test" value="test connection" type="submit" />
                                        <input name="submit_send" value="send" type="submit" />
                                    </form>
                                    * - opcjonalne

                                </div>

                            </div>
                        </div>
                    </section>
                </div>
                <aside class="secondary">
                    <section class="module module-narrow module-shallow">
                        <?= $this->partial('advert/advert/partial/offer.phtml'); ?>
                    </section>
                </aside>
            </div>
        </section>
    </section>
</section>