<div class="container-table">
    <div class="pricing-table">
        <div class="pricing-table-header">
            <h1>Free</h1>
        </div>
        
        <div class="pricing-table-content">
            <ul>
                <li><strong>1</strong> Ogłoszenia</li>
                <li><strong>5</strong> Email Addresses</li>
                <li><strong>3</strong> Subdomains</li>
                <li><strong>1</strong> MySQL Databases</li>
            </ul>
        </div>
        
        <div class="pricing-table-footer">
            <h2><sup>Zł </sup>0.00</h2>
            <p>miesięcznie</p>
            <a href="#">Dodaj Pakiet</a>
        </div>
    </div>
    <div class="pricing-table">
        <div class="pricing-table-header">
            <h1>Standard</h1>
        </div>
        
        <div class="pricing-table-content">
            <ul>
                <li><strong>3</strong> Ogłoszenia</li>
                <li><strong>5</strong> Email Addresses</li>
                <li><strong>3</strong> Subdomains</li>
                <li><strong>1</strong> MySQL Databases</li>
            </ul>
        </div>
        
        <div class="pricing-table-footer">
            <h2><sup>Zł </sup>19.99</h2>
            <p>miesięcznie</p>
            <a href="#">Kup Pakiet</a>
        </div>
    </div>
    
    <div class="pricing-table">
        <div class="pricing-table-header">
            <h1>Professional</h1>
        </div>
        
        <div class="pricing-table-content">
            <ul>
                <li><strong>10</strong> Ogłoszeń</li>
                <li><strong>20</strong> Email Addresses</li>
                <li><strong>10</strong> Subdomains</li>
                <li><strong>30</strong> MySQL Databases</li>
            </ul>
        </div>
        
        <div class="pricing-table-footer">
            <h2><sup>Zł </sup>59.99</h2>
            <p>miesięcznie</p>
            <a href="#">Kup Pakiet</a>
        </div>
    </div>
    
    <div class="pricing-table">
        <div class="pricing-table-header">
            <h1>Premium</h1>
        </div>
        
        <div class="pricing-table-content">
            <ul>
                <li><strong>50</strong> Ogłoszeń</li>
                <li><strong>50</strong> Email Addresses</li>
                <li><strong>20</strong> Subdomains</li>
                <li><strong>50</strong> MySQL Databases</li>
            </ul>
        </div>
        
        <div class="pricing-table-footer">
            <h2><sup>Zł </sup>129.99</h2>
            <p>miesięcznie</p>
            <a href="#">Kup Pakiet</a>
        </div>
    </div>
</div>