<section role="main" id="main">
    <section class="container">
        <section class="row featured-items">

            <div class="flash-messages">
                <?php if ($this->flashMessenger()->getErrorMessages()): ?>
                    <?php foreach ($this->flashMessenger()->getErrorMessages() as $message): ?>
                        <div class="alert alert-danger text-center">
                            <?php echo $message; ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>

                <?php if ($this->flashMessenger()->getSuccessMessages()): ?>
                    <?php foreach ($this->flashMessenger()->getSuccessMessages() as $message): ?>
                        <div class="alert alert-success text-center">
                            <?php echo $message; ?>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>

            <div class="toolbar">
                <ol class="breadcrumb">
                    <li class="home"><a href="/"><i class="fa fa-home"></i><span> Home</span></a></li>
                    <li class="active"><a href="/user/login" class=" active">Panel Logowanie</a></li>
                </ol>
            </div>
            <div class="wrapper">
                <div class="primary">
                    <section class="module">
                        <div class="module-content">
                            <h2 class="page-heading">Przypomnienie Hasła</h2>
                            <form class="form-horizontal" role="form" method="POST" action="<?= $this->url('user/reset') ?>">
                                <div class="form-group">
                                    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                                    <div class="col-sm-6">
                                        <input type="email" class="form-control" name="email" placeholder="" />
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <button type="submit" class="btn btn-primary">Wyślij Nowe Hasło</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </section>
                </div>
                <aside class="secondary">
                    <section class="module module-narrow module-shallow">
                        <h2 class="module-heading">Nie posiadasz Konta?</h2>
                        <div class="module-content">
                            <p>Aby móc korzystać z serwisu, potrzebne jest zarejestrowanie firmy w naszym serwisie.</p>
                            <p class="action">
                                <a href="<?= $this->url('company/register'); ?>" class="btn">Zarejestruj Firmę</a>
                            </p>
                        </div>
                    </section>

                    <section class="module module-narrow module-shallow">
                        <h2 class="module-heading">Zaloguj się?</h2>
                        <div class="module-content">
                            <p>Posiadasz już konto w naszym serwisie, zaloguj się by móc korzystać z pełnej funkcjonalności.</p>
                            <p class="action">
                                <a href="<?= $this->url('user/login'); ?>" class="btn">Zaloguj się</a>
                            </p>
                        </div>
                    </section>
                </aside>
            </div>
        </section>
    </section>
</section>
