<section role="main" id="main">
  <section class="container">
    <section class="row featured-items">

    <div class="flash-messages">
        <?php if ($this->flashMessenger()->getErrorMessages()): ?>
            <?php foreach ($this->flashMessenger()->getErrorMessages() as $message): ?>
                <div class="alert alert-danger text-center">
                    <?php echo $message; ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>

        <?php if ($this->flashMessenger()->getSuccessMessages()): ?>
            <?php foreach ($this->flashMessenger()->getSuccessMessages() as $message): ?>
                <div class="alert alert-success text-center">
                    <?php echo $message; ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>

    <div class="toolbar">
        <ol class="breadcrumb">
            <li class="home"><a href="/"><i class="fa fa-home"></i><span> Home</span></a></li>
            <li class="active"><a href="/user/login" class=" active">Panel Logowanie</a></li>
        </ol>
    </div>
    <div class="wrapper">
        <div class="primary">
            <section class="module">
                <div class="module-content">
                    <h2 class="page-heading">Panel Logowania</h2>
                    <form class="form-horizontal" role="form" method="POST" action="<?= $this->url('user/login') ?>">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-6">
                                <input type="email" class="form-control" name="identity" placeholder="" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                            <div class="col-sm-6">
                                <input type="password" class="form-control" name="credential" placeholder="" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <div class="checkbox">
                                    <label>
                                        <input type="hidden" name="remember" value="0" />
                                        <input type="checkbox" name="remember" value="1" /> Remember me
                                    </label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-primary">Zaloguj się</button>
                            </div>
                        </div>
                    </form>
                </div>
            </section>
        </div>
        <aside class="secondary">
            <section class="module module-narrow module-shallow">
                <h2 class="module-heading">Nie posiadasz Konta?</h2>
                <div class="module-content">
                    <p>Aby móc korzystać z serwisu, potrzebne jest zarejestrowanie firmy w naszym serwisie.</p>
                    <p class="action">
                        <a href="<?= $this->url('company/register'); ?>" class="btn">Zarejestruj Firmę</a>
                    </p>
                </div>
            </section>

            <section class="module module-narrow module-shallow">
                <h2 class="module-heading">Zapomniałeś hasła?</h2>
                <div class="module-content">
                    <p>Żaden problem, w łatwy sposób pozwalimy Ci je zmienić.</p>
                    <p class="action">
                        <a href="<?= $this->url('user/changepassword'); ?>" class="btn">Przypomnij Hasło</a>
                    </p>
                </div>
            </section>
        </aside>
    </div>
    </section>
  </section>
</section>
