<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('user/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'loginForm');
$form->setAttribute('id', 'login-form-user-show');
?>
<section class='container'>
<div class="contents">
  <div class="login--user">
    <form id="login-form-user-hide" class="loginForm <?php if($this->id !== 'password') echo 'hide'; ?>" method="POST" action="<?= $this->url('user/reset') ?>">
      <h1>Enter your email</h1>


      <ul class="userLogin">
        <li class="loginUsername">
          <input type="text" value="" placeholder="Email" class="login_username" name="email">
        </li>
      </ul>

      <div class="formFooter">
        <div class="formFooterButtons">

          <input type="submit" value="Send Password" class="login_submit formFooterButtons rounded Button primary Module large hasText btn" name="submit">
        </div>

        <span class="loginpanel">Log In Panel</span>
      </div>      
    </form>
    <?php if($this->id !== 'password'): ?>
    <?php echo $this->form()->openTag($form) ?>
    <h1>Log in to Kwik Learning</h1>
    <?php if ($this->flashMessenger()->getInfoMessages()): ?>
      <?php foreach ($this->flashMessenger()->getInfoMessages() as $message): ?>
        <div class="alert">
          <?php echo $message; ?>
        </div>
      <?php endforeach; ?>
    <?php endif; ?>

    <?php if ($this->flashMessenger()->getErrorMessages()): ?>
      <?php foreach ($this->flashMessenger()->getErrorMessages() as $message): ?>
        <div class="alert alert-error">
          <?php echo $message; ?>
        </div>
      <?php endforeach; ?>
    <?php endif; ?>
    
    <?php if ($this->flashMessenger()->getSuccessMessages()): ?>
      <?php foreach ($this->flashMessenger()->getSuccessMessages() as $message): ?>
        <div class="alert alert-success">
          <?php echo $message; ?>
        </div>
      <?php endforeach; ?>
    <?php endif; ?>

    <ul class="userLogin">
      <li class="loginUsername">
        <?php echo $this->formRow($form->get('identity')) ?>
      </li>
      <li class="loginPassword">
        <?php echo $this->formRow($form->get('credential')) ?>
      </li>
      <li class="loginRemember">
        <?php echo $this->formRow($form->get('remember')) ?>
        <span>Remember me</span>
      </li>
    </ul>

    <div class="formFooter">
      <div class="formFooterButtons">
        <?php if ($this->redirect): ?>
          <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <?php echo $this->formSubmit($form->get('submit')) ?>
      </div>

      <span class="forgotPassword">Forgot your password?</span>
    </div>
    <?php echo $this->form()->closeTag() ?>
    <?php endif; ?>
  </div>
</div>
</section>
