<section role="main" id="main">
    <section class="container">
        <section class="row featured-items">

            <?= $this->partial('user/user/partial/top_message.phtml'); ?>
            <?php
                $pakiet = $this->getRepos('Company\Entity\BundleDetails')->find($this->bundlePayments->getPakiet());
            ?>
            <div class="toolbar">
                <ol class="breadcrumb">
                    <li class="home"><a href="/"><i class="fa fa-home"></i><span> Home</span></a></li>
                    <li class="active"><a href="/user/login" class=" active">Firma</a></li>
                    <li class="active"><a href="/user/profile" class=" active">Profil</a></li>
                </ol>
            </div>
            <div class="wrapper">
                <div class="primary">
                    <section class="module">
                        <div class="module-content dashboard-profile dis-table col-lg-12">
                            <div class="col-lg-12 mar-top15">
                                <h3>Ogłoszenia <button type="button" link="<?= $this->url('advert/dashboard') ?>" class="buttonPoint btn btn-primary btn-xs pull-right">Zarządzanie Ogłoszeniami</button></h3>
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th>Nazwa</th>
                                        <th>Kategoria</th>
                                        <th>Publikacja</th>
                                        <th>Oferty</th>
                                        <th>Akcja</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td><a class="name" href="#">Nowe duże zgary</a></td>
                                        <td>Metale</td>
                                        <td>23/10/2014 12:34:12</td>
                                        <td><span class="labelbox grey">0</span></td>
                                        <td><button type="button" class="btn btn-primary btn-xs">Edytuj</button></td>
                                    </tr>
                                    <tr>
                                        <td><a class="name" href="#">Sprzedam super ciężarówkę miedzi</a></td>
                                        <td>Metale</td>
                                        <td>23/10/2014 12:34:12</td>
                                        <td><span class="labelbox grey">0</span></td>
                                        <td><button type="button" class="btn btn-primary btn-xs">Edytuj</button></td>
                                    </tr>
                                    <tr>
                                        <td><a class="name" href="#">Duży zakład pokryty złotem do sprzedania</a></td>
                                        <td>Metale</td>
                                        <td>23/10/2014 12:34:12</td>
                                        <td><span class="labelbox green">9</span></td>
                                        <td><button type="button" class="btn btn-primary btn-xs">Edytuj</button></td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-lg-12">
                                <h3>Tranzacje</h3>
                                <table class="table table-hover">
                                    <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Username</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>1</td>
                                        <td>Mark</td>
                                        <td>Otto</td>
                                        <td>@mdo</td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>Jacob</td>
                                        <td>Thornton</td>
                                        <td>@fat</td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td colspan="2">Larry the Bird</td>
                                        <td>@twitter</td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </section>
                </div>
                <aside class="secondary dashboard-profile">
                    <section class="module module-narrow module-shallow">
                        <h2 class="module-heading">Informacje</h2>
                        <div class="module-content">
                            <ul class="list-unstyled">
                                <li><strong>Pakiet:</strong> <span class="text-right"><span class="pakiet pakiet-premium"><?= $pakiet->getName(); ?></span></span></li>
                                <li><strong>Ranking:</strong>
                                        <span>
                                            <?= \Company\Entity\Company::rank($this->company->getRank());  ?>
                                        </span></li>
                                <li><strong>Propozycje:</strong> <span class="text-right">10</span></li>
                                <li><strong>Oferty:</strong> <span class="text-right">10</span></li>
                                <li><strong>Wiadomości:</strong> <span class="text-right">4</span></li>
                            </ul>
                        </div>
                    </section>
                    <section class="module module-narrow module-shallow">
                        <h2 class="module-heading">Magazyn</h2>
                        <div class="module-content">

                        </div>
                    </section>
                    <section class="module module-narrow module-shallow">
                        <h2 class="module-heading">Płatności
                            <?php if(!$this->bundlePayments->getPaid()): ?>
                                <span class="labelbox red pull-right"><?= -$this->bundlePayments->getAmount() ?> zł</span>
                            <?php else: ?>
                                <span class="labelbox green pull-right">Brak Należności</span>
                            <?php endif; ?></h2>
                        <div class="module-content">
                            <ul class="list-unstyled">
                                <li><strong>Pakiet:</strong> <span class="text-right color-red"><b><?= $this->bundlePayments->getAmount() ?> zł</b></span></li>
                                <li><strong>Tranzakcje:</strong> <span class="text-right">0 zł</span></li>
                                <li><strong>Transport:</strong> <span class="text-right">0 zł</span></li>
                                <li><strong>Dodatki:</strong> <span class="text-right">0 zł</span></li>
                                <li><strong>Poleceni:</strong> <span class="text-right color-green"><b>+20 zł</b></span></li>
                            </ul>
                        </div>
                    </section>
                </aside>
            </div>
        </section>
    </section>
</section>