<section role="main" id="main">
    <section class="container">
        <section class="row featured-items">

            <div class="flash-messages">
                <div class="alert alert-warning text-center">
                    <p>Nie możesz korzystać z wybrane pakietu. Pakiet jest <strong><abbr title="Przejdź do zakładki Płatności aby w szybki sposób móc aktywować usługę.">Nieaktywny</abbr></strong>. Opłać pakiet by móc w pełni korzystać z funkcjonalności serwisu.</p>
                </div>
            </div>
            <div class="toolbar">
                <ol class="breadcrumb">
                    <li class="home"><a href="/"><i class="fa fa-home"></i><span> Home</span></a></li>
                    <li class="active"><a href="/user/login" class=" active">Firma</a></li>
                    <li class="active"><a href="/user/profile" class=" active">Ustawienia</a></li>
                </ol>
            </div>
            <div class="wrapper">
                <div class="primary">
                    <section class="module">
                        <div class="module-content dis-table col-lg-12">
                            <div class="col-lg-12">

                                    <div class="page-header mar-top0">
                                        <h4>Dane Firmowe</h4>
                                    </div>

                                    <form class="form-horizontal seperator">
                                        <div class="form-group">
                                            <label class="col-md-4 control-label" for="name">Nazwa Firmy:</label>
                                            <div class="col-md-6">
                                                <input class="form-control input-md" name="name" id="name" type="text" value="<?= $this->company->getName(); ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-md-4 control-label" for="nip">NIP:</label>
                                            <div class="col-md-6">
                                                <input class="form-control input-md" id="nip" name="nip" type="text" disabled="disabled" value="<?= $this->company->getNip(); ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-md-4 control-label" for="regon">Regon:</label>
                                            <div class="col-md-6">
                                                <input class="form-control input-md" id="regon" name="regon" type="text" disabled="disabled" value="<?= $this->company->getRegon(); ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-md-4 control-label" for="country">Państwo:</label>
                                            <div class="col-md-6">
                                                <input class="form-control input-md" id="country" name="country" type="text" value="<?= $this->company->getCountry(); ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-md-4 control-label" for="district">Region:</label>
                                            <div class="col-md-6">
                                                <input class="form-control input-md" id="district" name="district" type="text" value="" />
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-md-4 control-label" for="city">Miasto:</label>
                                            <div class="col-md-6">
                                                <input class="form-control input-md" id="city" name="city" type="text" value="<?= $this->company->getCity(); ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-md-4 control-label" for="address">Adres:</label>
                                            <div class="col-md-6">
                                                <input class="form-control input-md" id="address" name="address" type="text" value="<?= $this->company->getAddress(); ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label class="col-md-4 control-label" for="post_code">Kod pocztowy:</label>
                                            <div class="col-md-6">
                                                <input class="form-control input-md" id="post_code" name="post_code" type="text" value="<?= $this->company->getPostCode(); ?>" />
                                            </div>
                                        </div>

                                        <div class="form-group border-0 padding-0">
                                            <label for="description" class="col-sm-4 control-label"></label>

                                            <div class="col-sm-6">
                                                <button id="add-advert" name="preview" class="btn btn-primary">Zapisz</button>
                                            </div>
                                        </div>

                                    </form>

                            </div>
                        </div>
                    </section>
                </div>
                <aside class="secondary">
                    <section class="module module-narrow module-shallow">
                        <?= $this->partial('company/company/partial/settings.phtml', array(
                            'action' => $this->action,
                            'method' => $this->method
                        )); ?>
                    </section>
                </aside>
            </div>
        </section>
    </section>
</section>