<section role="main" id="main">
    <section class="container">
        <section class="row featured-items">

            <div class="flash-messages">
                <div class="alert alert-warning text-center">
                    <p>Nie możesz korzystać z wybrane pakietu. Pakiet jest <strong><abbr title="Przejdź do zakładki Płatności aby w szybki sposób móc aktywować usługę.">Nieaktywny</abbr></strong>. Opłać pakiet by móc w pełni korzystać z funkcjonalności serwisu.</p>
                </div>
            </div>
            <div class="toolbar">
                <ol class="breadcrumb">
                    <li class="home"><a href="/"><i class="fa fa-home"></i><span> Home</span></a></li>
                    <li class="active"><a href="/user/login" class=" active">Firma</a></li>
                    <li class="active"><a href="/user/profile" class=" active">Oferty</a></li>
                </ol>
            </div>
            <div class="wrapper">
                <div class="primary">
                    <section class="module">
                        <div class="module-content dashboard-profile dis-table col-lg-12">
                            <div class="col-lg-12">
                                <h3>Oferty</h3>
                                <?php foreach($this->adverts as $advert): ?>
                                    <table class="table offer-list">
                                        <thead>
                                        <tr>
                                            <th><?= $advert->getId(); ?></th>
                                            <th><?= $advert->getName(); ?></th>
                                            <th><?= $advert->getAmount(); ?></th>
                                            <?php $activeType = \Advert\Entity\Advert::getActiveType($advert->getActive()); ?>
                                            <th><?= $activeType->name; ?></th>
                                            <th><?= $advert->getCreated_at()->format('d/m/Y'); ?></th>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php if(isset($advert->offers)): ?>
                                            <?php foreach($advert->offers as $offer): ?>
                                                <tr>
                                                    <td><?= $offer->getId(); ?></td>
                                                    <td><?= $offer->getDescription(); ?></td>
                                                    <td>Kwota: <?= $offer->getAmount(); ?></td>
                                                    <td><?= \Advert\Entity\Offer::getNameOfType($offer->getType()); ?></td>
                                                    <td><?= $offer->getCreatedAt()->format('d/m/Y'); ?></td>
                                                    <td></td>
                                                    <td>
                                                        <button type="button" link="<?= $this->url('advert/edit', array('id' => $advert->getId())) ?>" class="buttonPoint btn btn-primary btn-xs">Akceptuj</button>
                                                        <button type="button" link="<?= $this->url('advert/edit', array('id' => $advert->getId())) ?>" class="buttonPoint btn btn-danger btn-xs">Odrzuć</button>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                        </tbody>
                                    </table>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </section>
                </div>
                <aside class="secondary">
                    <section class="module module-narrow module-shallow">
                        <?= $this->partial('advert/advert/partial/offer.phtml'); ?>
                    </section>
                </aside>
            </div>
        </section>
    </section>
</section>