<?= $this->doctype(); ?>
<?php
$module = explode('\\', $this->controller);
if($this->UserIdentity()){
    $locale = $this->UserIdentity()->getLocale();
}else{
    $locale = isset($_COOKIE['lang']) ? $_COOKIE['lang'] : 'pl_PL';
}
$lang = explode('_', $locale);
?>
<html lang="<?= $lang[0]; ?>">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <?php echo $this->headTitle('RecMet ' . $this->translate('Materials'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

    <!-- Bootstrap core CSS -->
    <link href="<?= $this->basePath(); ?>/css/bootstrap.min.css" rel="stylesheet">

    <!-- Animation CSS -->
    <link href="<?= $this->basePath(); ?>/css/animate.min.css" rel="stylesheet">

    <link href="<?= $this->basePath(); ?>/css/font-awesome.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="<?= $this->basePath(); ?>/css/home.css" rel="stylesheet">
</head>
<body id="page-top">
<div class="navbar-wrapper">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->basePath(); ?>">RecMetals</a>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img id="flags" src="<?= $this->basePath(); ?>/img/flags/<?= strtolower($lang[1]); ?>.png" /></a>
                        <ul class="dropdown-menu">
                            <li><a href="#" onclick="setLanguage('pl_PL')"><img src="<?= $this->basePath(); ?>/img/flags/pl.png" /> Polski </a></li>
                            <li class="divider"></li>
                            <li><a href="#" onclick="setLanguage('en_US')"><img src="<?= $this->basePath(); ?>/img/flags/us.png" /> English </a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="page-scroll" href="#page-top"><?= $this->translate('Home') ?></a></li>
                    <li><a class="page-scroll" href="#features"><?= $this->translate('Features') ?></a></li>
                    <li><a class="page-scroll" href="#team"><?= $this->translate('Team') ?></a></li>
                    <li><a class="page-scroll" href="#testimonials"><?= $this->translate('Testimonials') ?></a></li>
                    <li><a class="page-scroll" href="#pricing"><?= $this->translate('Pricing') ?></a></li>
                    <li><a class="page-scroll" href="#contact"><?= $this->translate('Contact') ?></a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div id="inSlider" class="carousel slide carousel-fade" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#inSlider" data-slide-to="0" class="active"></li>
        <li data-target="#inSlider" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="container">
                <div class="carousel-caption">
                    <h1>We craft<br/>
                        brands, web apps,<br/>
                        and user interfaces<br/>
                        we are IN+ studio</h1>
                    <p>Lorem Ipsum is simply dummy text of the printing.</p>
                    <p>
                        <a class="btn btn-lg btn-primary" href="#" role="button">READ MORE</a>
                        <a class="caption-link" href="#" role="button">Inspinia Theme</a>
                    </p>
                </div>
                <div class="carousel-image wow zoomIn">
                    <img src="<?= $this->basePath(); ?>/img/home/laptop.png" alt="laptop"/>
                </div>
            </div>
            <!-- Set background for slide in css -->
            <div class="header-back one"></div>

        </div>
        <div class="item">
            <div class="container">
                <div class="carousel-caption blank">
                    <h1>We create meaningful <br/> interfaces that inspire.</h1>
                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
                    <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                </div>
            </div>
            <!-- Set background for slide in css -->
            <div class="header-back two"></div>
        </div>
    </div>
    <a class="left carousel-control" href="#inSlider" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#inSlider" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<?php echo $this->content; ?>

<section id="contact" class="gray-section contact">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>Contact Us</h1>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.</p>
            </div>
        </div>
        <div class="row m-b-lg">
            <div class="col-lg-3 col-lg-offset-3">
                <address>
                    <strong><span class="navy">Company name, Inc.</span></strong><br/>
                    795 Folsom Ave, Suite 600<br/>
                    San Francisco, CA 94107<br/>
                    <abbr title="Phone">P:</abbr> (123) 456-7890
                </address>
            </div>
            <div class="col-lg-4">
                <p class="text-color">
                    Consectetur adipisicing elit. Aut eaque, totam corporis laboriosam veritatis quis ad perspiciatis, totam corporis laboriosam veritatis, consectetur adipisicing elit quos non quis ad perspiciatis, totam corporis ea,
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <a href="mailto:test@email.com" class="btn btn-primary">Send us mail</a>
                <p class="m-t-sm">
                    Or follow us on social platform
                </p>
                <ul class="list-inline social-icon">
                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg m-b-lg">
                <p><strong>&copy; <?= date('Y') ?> RecMetals.com by Recol Investment Group Ltd.</strong><br/><?= $this->translate('All rights reserved.') ?></p>
            </div>
        </div>
    </div>
</section>

<script src="<?= $this->basePath(); ?>/js/home/jquery-2.1.1.js"></script>
<script src="<?= $this->basePath(); ?>/js/home/pace.min.js"></script>
<script src="<?= $this->basePath(); ?>/js/bootstrap.min.js"></script>
<script src="<?= $this->basePath(); ?>/js/home/classie.js"></script>
<script src="<?= $this->basePath(); ?>/js/home/cbpAnimatedHeader.js"></script>
<script src="<?= $this->basePath(); ?>/js/home/wow.min.js"></script>
<script src="<?= $this->basePath(); ?>/js/home/inspinia.js"></script>

<script>
    function setLanguage(lang) {
        $.ajax({
            type: "POST",
            url: '<?= $this->url('system/lang') ?>',
            dataType: "json",
            data: {'lang': lang}
        })
            .success(function (msg) {
                if(msg.success){
                    if(msg.param) {
                        location.reload();
                    }
                }
            });
        return false;
    }
/*
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-4625583-2', 'webapplayers.com');
    ga('send', 'pageview');
*/

</script>
</body>
</html>
