<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('RecMet ' . $this->translate('Materials'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

    <?php
    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . '/css/styles.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/tinymce.css')
    ?>
<?php $this->headScript()
    ->prependFile($this->basePath() . '/js/tinymce.js', 'text/javascript', array())
    ->prependFile($this->basePath() . '/js/script.min.js', 'text/javascript', array())
    ->prependFile($this->basePath() . '/js/plugins.min.js', 'text/javascript', array())
    ->prependFile($this->basePath() . '/js/jquery.min.js', 'text/javascript', array()); ?>
      <?php echo $this->headScript(); ?>

  </head>
  <body>
    <!--[if lt IE 9]>
        <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
    <![endif]-->
    <header>
      <section class='container'>
        <section class='row'>
          <div class='col-md-2'>
              <a class="logo" href="<?= $this->url('home') ?>">
                RecMetals
              </a>
          </div>
          <div class='col-md-8'>
            <nav class='main-nav'>
              <ul class="hidden-phone">
                <li <?php if($this->action == ''): ?> class="active"<?php endif; ?>><a href="<?= $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                <li><a href="<?= $this->url('advert') ?>"><?php echo $this->translate('Ogłoszenia') ?></a></li>
                <li><a href="<?= $this->url('companies') ?>"><?php echo $this->translate('Firmy') ?></a></li>
                <li><a href="<?php //echo $this->url('jobs')   ?>"><?php echo $this->translate('Specjaliści') ?></a></li>
                <li><a href="<?php //echo $this->url('website')   ?>"><?php echo $this->translate('Strona') ?></a></li>
                <li><a href="<?php //echo $this->url('statistics')   ?>"><?php echo $this->translate('Giełda') ?></a></li>
                <li><a href="<?php //echo $this->url('support')   ?>"><?php echo $this->translate('Support') ?></a></li>
              </ul>
            </nav>
          </div>
          <?php if($this->UserIdentity()): ?>
            <div class='col-md-2'>
              <div class='header-buttons'>
                <a href="<?= $this->url('user/profile') ?>" class="add">Add</a>
                <a href="<?= $this->url('user/profile') ?>" class='profile'>Profile</a>
                <a href="#" class='contact'>Contact</a>
              </div>
            </div>
          <?php else: ?>
            <nav class='main-nav'>
              <ul class="hidden-phone">
                <li <?php if($this->action == 'login'): ?> class="active"<?php endif; ?>><a href="<?= $this->url('user/login') ?>">Zaloguj</a></li>
                <li <?php if($this->action == 'register' || $this->controller == 'prices'): ?> class="active"<?php endif; ?>><a href="<?= $this->url('company/register') ?>">Zarejestruj</a></li>
              </ul>
            </nav>
          <?php endif; ?>
        </section>
      </section>
    </header>
    <?php if($this->UserIdentity()): ?>
    <section class="subheader">
      <section class='container' style="height: 40px; line-height: 40px;">
        <div class="col-md-10">
          <ul class="list-inline submenu">
              <li><a href="<?= $this->url('user/profile') ?>">Profile</a></li>
              <li><a href="<?= $this->url('advert/offer') ?>">Oferty <span class="badge">1</span></a></li>
              <li><a href="<?= $this->url('advert/dashboard') ?>">Zarzadzanie Ogłoszeniami <span class="badge">3</span></a></li>
              <li><a href="<?= $this->url('advert/magazine') ?>">Magazyn <span class="badge">22</span></a></li>
              <li><a href="<?= $this->url('advert/transations') ?>">Transakcje <span class="badge">1</span></a></li>
              <li><a href="<?= $this->url('company/representatives') ?>">Przedstawiciele</a></li>
              <li><a href="<?= $this->url('company/payments') ?>">Płatności <span class="badge red">!</span></a></li>
              <li><a href="<?= $this->url('company/settings') ?>">Ustawienia</a></li>
          </ul>
        </div>
        <div class="col-md-2 text-right">
          <ul class="list-inline submenu">
              <li><a href="<?= $this->url('user/logout') ?>">Wyloguj</a></li>
          </ul>
        </div>
      </section>
    </section>
    <?php endif; ?>
    
    <?php echo $this->content; ?>
    
    <section id='sub-footer'>
      <section class='container'>
        <section class='row'>
          <div class='col-md-12'>
            <div class='copyright'>
              <p>&copy; 2014 - <?php echo date('Y') ?> by Recol Investment Group Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
          </div>
        </section>
      </section>
    </section>
<?php echo $this->inlineScript() ?>
  </body>
</html>
