<?php echo $this->doctype(); ?>
<?php
    $module = explode('\\', $this->controller);
    if($this->UserIdentity()){
        $locale = $this->UserIdentity()->getLocale();
    }else{
        $locale = isset($_COOKIE['lang']) ? $_COOKIE['lang'] : 'pl_PL';
    }
    $lang = explode('_', $locale);
?>
<html lang="en">
  <head>
      <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <?php echo $this->headTitle('RecMet ' . $this->translate('Materials'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>

    <?php
    $cssFile = $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'));
        $cssViewFile = strtolower($module[0]) . DIRECTORY_SEPARATOR . strtolower($this->action) . '.css';
        $cssFile->prependStylesheet($this->basePath() . '/css/views/' . $cssViewFile);
        $cssFile->prependStylesheet($this->basePath() . '/css/styles.min.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/css/tinymce.css')
        ->prependStylesheet($this->basePath() . '/css/plugins.css');

        echo $cssFile;
    ?>

    <?php
    $this->headScript()
    ->prependFile($this->basePath() . '/js/tinymce.js', 'text/javascript', array())
    ->prependFile($this->basePath() . '/js/script.min.js', 'text/javascript', array())
    ->prependFile($this->basePath() . '/js/plugins.min.js', 'text/javascript', array())
    ->prependFile($this->basePath() . '/js/jquery.min.js', 'text/javascript', array()); ?>
      <?php echo $this->headScript(); ?>

  </head>
  <body>
    <!--[if lt IE 9]>
        <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
    <![endif]-->
    <header>
      <section class='container'>
        <section class='row'>
          <div class='col-md-2' style="position: relative;">
              <a class="logo" href="<?= $this->url('home') ?>">
                RecMetals
              </a>
              <ul class="nav navbar-nav">
                  <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img id="flags" src="<?= $this->basePath(); ?>/img/flags/<?= strtolower($lang[1]); ?>.png" /></a>
                      <ul class="dropdown-menu">
                          <li><a href="" onclick="setLanguage('pl_PL')"><img src="<?= $this->basePath(); ?>/img/flags/pl.png" /> Polski </a></li>
                          <li class="divider"></li>
                          <li><a href="" onclick="setLanguage('en_US')"><img src="<?= $this->basePath(); ?>/img/flags/us.png" /> English </a></li>
                      </ul>
                  </li>
              </ul>
          </div>
            <?php
            $mainNav = array(
                array('url' => 'home', 'name' => $this->translate('Home'), 'action' => 'index'),
                array('url' => 'advert', 'name' => $this->translate('Adverts'), 'action' => 'advertList'),
                array('url' => 'companies', 'name' => $this->translate('Company'), 'action' => 'companiesList'),
                array('url' => 'site', 'name' => $this->translate('Site'), 'action' => 'site'),
                array('url' => 'support', 'name' => 'Support', 'action' => 'support')
            )
            ?>
          <div class='col-md-8'>
            <nav class='main-nav'>
              <ul class="hidden-phone">
                  <?php foreach($mainNav as $nav): ?>
                      <li <?php if($this->action == $nav['action']): ?> class="active"<?php endif; ?>><a href="<?= $this->url($nav['url']); ?>"><?= $nav['name']; ?></a></li>
                  <?php endforeach; ?>
              </ul>
            </nav>
          </div>
          <?php if($this->UserIdentity()): ?>
            <div class='col-md-2'>
              <div class='header-buttons'>
                <a href="<?= $this->url('advert/add'); ?>" class="add">Add</a>
                <a href="<?= $this->url('user/profile') ?>" class='profile'>Profile</a>
                <a href="<?= $this->url('message'); ?>" class='contact'>Contact</a>
              </div>
            </div>
          <?php else: ?>
            <nav class='main-nav'>
              <ul class="hidden-phone">
                <li <?php if($this->action == 'login'): ?> class="active"<?php endif; ?>><a href="<?= $this->url('user/login') ?>">Zaloguj</a></li>
                <li <?php if($this->action == 'register' || $this->controller == 'prices'): ?> class="active"<?php endif; ?>><a href="<?= $this->url('company/register') ?>">Zarejestruj</a></li>
              </ul>
            </nav>
          <?php endif; ?>
        </section>
      </section>
    </header>
    <?php if($this->UserIdentity()): ?>
    <section class="subheader">
      <section class='container' style="height: 40px; line-height: 40px;">
        <div class="col-md-10">
          <ul class="list-inline submenu">
              <li><a href="<?= $this->url('user/profile') ?>">Profile</a></li>
              <?php $offerCount = $this->getRepos('Advert\Entity\Offer')->getOfferCountNotSeen($this->UserIdentity()->getCompanyId()); ?>
              <li><a href="<?= $this->url('offer') ?>">Oferty <?php if($offerCount): ?><span class="badge"><?= $offerCount; ?></span><?php endif; ?></a></li>
              <li><a href="<?= $this->url('advert/dashboard') ?>">Zarzadzanie Ogłoszeniami <span class="badge">3</span></a></li>
              <li><a href="<?= $this->url('advert/magazine') ?>">Magazyn <span class="badge">22</span></a></li>
              <li><a href="<?= $this->url('advert/transations') ?>">Transakcje <span class="badge">1</span></a></li>
              <li><a href="<?= $this->url('company/payments') ?>">Płatności <span class="badge red">!</span></a></li>
              <li><a href="<?= $this->url('company/settings') ?>">Ustawienia</a></li>
          </ul>
        </div>
        <div class="col-md-2 text-right">
          <ul class="list-inline submenu">
              <li><a href="<?= $this->url('user/logout') ?>">Wyloguj</a></li>
          </ul>
        </div>
      </section>
    </section>
    <?php endif; ?>
    
    <?php echo $this->content; ?>
    
    <section id='sub-footer'>
      <section class='container'>
        <section class='row'>
          <div class='col-md-12'>
            <div class='copyright'>
              <p>&copy; 2014 - <?php echo date('Y') ?> by Recol Investment Group Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </div>
          </div>
        </section>
      </section>
    </section>
<?php echo $this->inlineScript() ?>
    <script type="text/javascript">
        function setLanguage(lang) {
            console.log(lang);
            $.ajax({
                type: "POST",
                url: '<?= $this->url('system/lang') ?>',
                dataType: "json",
                data: {'lang': lang}
            })
            .success(function (msg) {
                if(msg.success){
                    if(msg.param) {
                        location.reload();
                    }
                }
            });
            return false;
        }
    </script>
  </body>
</html>
