<h2 class="module-heading">Menu</h2>
<ul class="list-unstyled menu-grey">
    <li><a href="<?= $this->url('advert/dashboard') ?>" class="<?php if($this->action == 'dashboard'): ?>active<?php endif; ?>">Dashboard</a></li>
    <li><a href="<?= $this->url('advert/add') ?>" class="<?php if($this->action == 'add'): ?>active<?php endif; ?>">Dodaj Ogłoszenie</a></li>
    <li><a href="<?= $this->url('advert/manager') ?>" class="">Obserwowane</a></li>
    <li><a href="<?= $this->url('advert/manager') ?>" class="">Proponowane</a></li>
</ul>