<section role="main" id="main">
    <section class="container">
        <section class="row featured-items">

            <div class="flash-messages">
                <div class="alert alert-warning text-center">
                    <p>Nie możesz korzystać z wybrane pakietu. Pakiet jest <strong><abbr title="Przejdź do zakładki Płatności aby w szybki sposób móc aktywować usługę.">Nieaktywny</abbr></strong>. Opłać pakiet by móc w pełni korzystać z funkcjonalności serwisu.</p>
                </div>
            </div>
            <div class="toolbar">
                <ol class="breadcrumb">
                    <li class="home"><a href="/"><i class="fa fa-home"></i><span> Home</span></a></li>
                    <li class="active"><a href="/user/login" class=" active">Firma</a></li>
                    <li class="active"><a href="/user/profile" class=" active">Zarządzanie Ogłoszeniami</a></li>
                </ol>
            </div>
            <div class="wrapper">
                <div class="primary">
                    <section class="module">
                        <div class="module-content dis-table col-lg-12">
                            <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
                                <div class="col-lg-8">
                                    <div class="form-group">
                                        <label for="name" class="col-sm-4 control-label">Tytuł Ogłoszenia</label>
                                        <div class="col-sm-7">
                                            <input id="name" name="name" class="form-control input-md" type="text">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="category" class="col-sm-4 control-label">Kategoria</label>
                                        <div class="col-sm-7">
                                            <select id="category" name="category" class="form-control">
                                                <option value="1">Metale</option>
                                                <option value="2">Plastyki</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="description" class="col-sm-4 control-label">Treść</label>
                                        <div class="col-sm-7">
                                            <textarea class="form-control" rows="10" id="description" name="description"></textarea>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-4">

                                <div class="form-group">
                                    <label for="amount" class="col-sm-2 control-label">Cena</label>
                                    <div class="col-sm-10">
                                        <input id="amount" name="amount" class="form-control input-md" type="text">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="pieces" class="col-sm-2 control-label">Ilość</label>
                                    <div class="col-sm-10">
                                        <input id="weight" name="pieces" class="form-control input-md" type="text">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="checkbox-inline" for="advert_type">
                                        <input name="advert_type" id="checkboxes-0" value="1" type="checkbox">
                                        Wystawiam
                                    </label>
                                    <label class="checkbox-inline" for="advert_type">
                                        <input name="advert_type" id="checkboxes-1" value="2" type="checkbox">
                                        Poszukuje
                                    </label>
                                </div>

                                <div class="form-group">
                                    <label class="checkbox-inline" for="amount_type">
                                        <input name="amount_type" id="checkboxes-0" value="1" type="checkbox">
                                        Jednorazowo
                                    </label>
                                    <label class="checkbox-inline" for="amount_type">
                                        <input name="amount_type" id="checkboxes-1" value="2" type="checkbox">
                                        Miesiecznie
                                    </label>
                                </div>

                                <div class="form-group">
                                    <label for="images">Zdjęcia</label>
                                    <input id="images" name="images[]" multiple="multiple" class="input-file" type="file">
                                </div>

                                    </div>

                                <div class="form-group">
                                    <button id="add-advert" name="add-advert" class="btn btn-success">Dodaj Ogłoszenie</button>
                                </div>
                            </form>
                        </div>
                    </section>
                </div>
                <aside class="secondary">
                    <section class="module module-narrow module-shallow">
                        <?= $this->partial('advert/advert/partial/menu.phtml'); ?>
                    </section>
                </aside>
            </div>
        </section>
    </section>
</section>