<section id='page-title'>
  <section class='container'>
    <section class='row'>
      <div class='col-md-6'>
        <h1>Search Results</h1>
        <p>In sit amet arcu quis dolor adipiscing laoreet sed sit amet arcu. Proin non adipiscing felis.</p>
      </div>
    </section>
  </section>
</section>
<section id='main' role='main'>
  <section class='container'>
    <section class='row tab-finder'>
      <div class='col-md-12'>
        <div class="tabbable">
          <ul class="nav nav-tabs">
            <li class="active first-tab"><a href="#tab1" data-toggle="tab">For Sale</a></li>
            <li><a href="#tab2" data-toggle="tab">For Rent</a></li>
            <li><a href="#tab3" data-toggle="tab">Foreclosures</a></li>
            <li class='last-tab'><a href="#tab4" data-toggle="tab">New Homes</a></li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active" id="tab1">
              <div class='inner'>
                <form action="#">
                  <input type="text" name='search-string' class='search-string' placeholder="eg. 'Miami', 'Los Angeles'"/>
                  <input type="text" name='search-year' class='search-year' placeholder="Year"/>
                  <select name="search-bedrooms" class='col-md-2 selectpicker search-select'>
                    <option>Bedrooms</option>
                    <option>1</option>
                    <option>2</option>
                  </select>
                  <select name="search-bathrooms" class='col-md-2 selectpicker search-select'>
                    <option>Bathrooms</option>
                    <option>1</option>
                    <option>2</option>
                  </select>
                  <input type="text" name='search-min-price' class='col-md-2 search-price no-margin' placeholder="Min. Price"/>
                  <span class='line-divider'>&ndash;</span>
                  <input type="text" name='search-max-price' class='col-md-2 search-price' placeholder="Max. Price"/>
                  <button type="submit" class='btn btn-primary search-property'><i class="icon-search icon-white"></i> Search Property</button>
                </form>
              </div>
            </div>
            <div class="tab-pane" id="tab2">
              <div class='inner'>
                <form action="#">
                  <input type="text" name='search-string' class='search-string' placeholder="eg. 'Miami', 'Los Angeles'"/>
                  <input type="text" name='search-year' class='search-year' placeholder="Year"/>
                  <select name="search-bedrooms" class='col-md-2 selectpicker search-select'>
                    <option>Bedrooms</option>
                    <option>1</option>
                    <option>2</option>
                  </select>
                  <select name="search-bathrooms" class='col-md-2 selectpicker search-select'>
                    <option>Bathrooms</option>
                    <option>1</option>
                    <option>2</option>
                  </select>
                  <input type="text" name='search-min-price' class='col-md-2 search-price no-margin' placeholder="Min. Price"/>
                  <span class='line-divider'>&ndash;</span>
                  <input type="text" name='search-max-price' class='col-md-2 search-price' placeholder="Max. Price"/>
                  <button type="submit" class='btn btn-primary search-property'><i class="icon-search icon-white"></i> Search Property</button>
                </form>
              </div>
            </div>
            <div class="tab-pane" id="tab3">
              <div class='inner'>
                <form action="#">
                  <input type="text" name='search-string' class='search-string' placeholder="eg. 'Miami', 'Los Angeles'"/>
                  <input type="text" name='search-year' class='search-year' placeholder="Year"/>
                  <select name="search-bedrooms" class='col-md-2 selectpicker search-select'>
                    <option>Bedrooms</option>
                    <option>1</option>
                    <option>2</option>
                  </select>
                  <select name="search-bathrooms" class='col-md-2 selectpicker search-select'>
                    <option>Bathrooms</option>
                    <option>1</option>
                    <option>2</option>
                  </select>
                  <input type="text" name='search-min-price' class='col-md-2 search-price no-margin' placeholder="Min. Price"/>
                  <span class='line-divider'>&ndash;</span>
                  <input type="text" name='search-max-price' class='col-md-2 search-price' placeholder="Max. Price"/>
                  <button type="submit" class='btn btn-primary search-property'><i class="icon-search icon-white"></i> Search Property</button>
                </form>
              </div>
            </div>
            <div class="tab-pane" id="tab4">
              <div class='inner'>
                <form action="#">
                  <input type="text" name='search-string' class='search-string' placeholder="eg. 'Miami', 'Los Angeles'"/>
                  <input type="text" name='search-year' class='search-year' placeholder="Year"/>
                  <select name="search-bedrooms" class='col-md-2 selectpicker search-select'>
                    <option>Bedrooms</option>
                    <option>1</option>
                    <option>2</option>
                  </select>
                  <select name="search-bathrooms" class='col-md-2 selectpicker search-select'>
                    <option>Bathrooms</option>
                    <option>1</option>
                    <option>2</option>
                  </select>
                  <input type="text" name='search-min-price' class='col-md-2 search-price no-margin' placeholder="Min. Price"/>
                  <span class='line-divider'>&ndash;</span>
                  <input type="text" name='search-max-price' class='col-md-2 search-price' placeholder="Max. Price"/>
                  <button type="submit" class='btn btn-primary search-property'><i class="icon-search icon-white"></i> Search Property</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class='row featured-items'>
      <div class='col-md-12'>
        <h2>Ogłoszenia Specjalne</h2>
        <div class='featured-items-slider'>
          <ul class='slides'>
            <li>
              <div class='row'>
                <div class='col-md-3 featured-item-wrapper'>
                  <div class='featured-item'>
                    <div class='top'>
                      <div class='inner-border'>
                        <div class='inner-padding'>
                          <figure>
                            <img src="img/photos/4834194361_85d5c4a5e0_b.jpg" alt="" />
                            <div class='banner'>For Rent</div>
                            <a href="property.html" class='figure-hover'>Zoom</a>
                          </figure>
                          <h3><a href="property.html">1 Central Park S</a></h3>
                          <p>Las Vegas, NV</p>
                        </div>
                      </div>
                      <i class='bubble'></i>
                    </div>
                    <div class='bottom'>
                      <div class='inner-border'>
                        <div class='inner-padding'>
                          <p>3 beds  +  1 bath  +  100 sqft</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class='star-rating'>
                    <button class='star blue'>1 Star</button>
                    <button class='star active'>2 Star</button>
                    <button class='star active'>3 Star</button>
                    <button class='star'>4 Star</button>
                    <button class='star'>5 Star</button>
                  </div>
                  <div class='price-wrapper'>
                    <div class='price'>$2,150</div>
                    <div class='rate'>/mo</div>
                  </div>
                </div>
                <div class='col-md-3 featured-item-wrapper'>
                  <div class='featured-item'>
                    <div class='top'>
                      <div class='inner-border'>
                        <div class='inner-padding'>
                          <figure>
                            <img src="img/photos/4834197589_84d75a42bd_b.jpg" alt="" />
                            <div class='banner'>For Sale</div>
                            <a href="property.html" class='figure-hover'>Zoom</a>
                          </figure>
                          <h3><a href="property.html">555 Malcolm X Blvd</a></h3>
                          <p>Los Angeles, CA</p>
                        </div>
                      </div>
                      <i class='bubble'></i>
                    </div>
                    <div class='bottom'>
                      <div class='inner-border'>
                        <div class='inner-padding'>
                          <p>3 beds  +  1 bath  +  100 sqft</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class='star-rating'>
                    <button class='star blue'>1 Star</button>
                    <button class='star active'>2 Star</button>
                    <button class='star active'>3 Star</button>
                    <button class='star'>4 Star</button>
                    <button class='star'>5 Star</button>
                  </div>
                </div>
                <div class='col-md-3 featured-item-wrapper'>
                  <div class='featured-item'>
                    <div class='top'>
                      <div class='inner-border'>
                        <div class='inner-padding'>
                          <figure>
                            <img src="img/photos/4834201025_e7f66118eb_b.jpg" alt="" />
                            <div class='banner'>For Rent</div>
                            <a href="property.html" class='figure-hover'>Zoom</a>
                          </figure>
                          <h3><a href="property.html">520 W 110th St</a></h3>
                          <p>Las Vegas, NV</p>
                        </div>
                      </div>
                      <i class='bubble'></i>
                    </div>
                    <div class='bottom'>
                      <div class='inner-border'>
                        <div class='inner-padding'>
                          <p>4 beds  +  2 baths  +  245 sqft</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class='star-rating'>
                    <button class='star active'>1 Star</button>
                    <button class='star active'>2 Star</button>
                    <button class='star active'>3 Star</button>
                    <button class='star active'>4 Star</button>
                    <button class='star active'>5 Star</button>
                  </div>
                  <div class='price-wrapper'>
                    <div class='price'>$17,000</div>
                    <div class='rate'>/year</div>
                  </div>
                </div>
                <div class='col-md-3 featured-item-wrapper'>
                  <div class='featured-item'>
                    <div class='top'>
                      <div class='inner-border'>
                        <div class='inner-padding'>
                          <figure>
                            <img src="img/photos/4834203945_3e56a09048_b.jpg" alt="" />
                            <a href="property.html" class='figure-hover'>Zoom</a>
                          </figure>
                          <h3><a href="property.html">100 W 57th St</a></h3>
                          <p>Los Angeles, CA</p>
                        </div>
                      </div>
                      <i class='bubble'></i>
                    </div>
                    <div class='bottom'>
                      <div class='inner-border'>
                        <div class='inner-padding'>
                          <p>2 beds  +  2 baths + 168 sqft</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class='star-rating'>
                    <button class='star active'>1 Star</button>
                    <button class='star active'>2 Star</button>
                    <button class='star active'>3 Star</button>
                    <button class='star active'>4 Star</button>
                    <button class='star active'>5 Star</button>
                  </div>
                  <div class='price-wrapper'>
                    <div class='price'>$3,400</div>
                    <div class='rate'>/mo</div>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <i class='content-bubble'></i>
    </section>
  </section>
</section>
<section id='content'>
  <section class='container'>
    <section class='row featured-items'>
      <section class='col-md-9'>
        <div class='row'>
          <div class='col-md-12'>
            <div class='top-bar'>
              <div class='bar-title'>
                <div class='inner'>
                  <div class='pull-left custom-margin'>
                    <strong>1</strong> - <strong>9</strong> of <strong>1,075</strong> results for <strong>Oxford</strong> property <strong>For Sale</strong>
                  </div>
                  <div class='pull-right results-per-page custom-margin'>
                    <span class='text-line'>Results per page:</span>
                    <ul>
                      <li class='active'><a href="#">9</a></li>
                      <li>|</li>
                      <li><a href="#">18</a></li>
                      <li>|</li>
                      <li><a href="#">27</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class='bar-bottom'>
                <div class='inner'>
                  <div class='pull-left custom-margin'>
                    <span class='text-line'>Sort by:</span>
                    <select class='selectpicker'>
                      <option value="relevance">Relevance</option>
                      <option value="date">Date</option>
                    </select>
                  </div>
                  <div class='pull-right view-type custom-margin'>
                    <span class='text-line'>View:</span>
                    <ul>
                      <li><a href="search-grid.html" class='grid'>Grid</a></li>
                      <li class='active'><a href="search-list.html" class='list'>List</a></li>
                      <li class='last-element'><a href="search-location.html" class='location'>Location</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class='row'>
          <div class='col-md-12 featured-item-list'>
            <div class='featured-item featured-list'>
              <div class='top'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <figure>
                      <img src="img/photos/4834194361_85d5c4a5e0_b.jpg" alt="" />
                      <div class='banner'>For Sale</div>
                      <a href="property.html" class='figure-hover'>Zoom</a>
                    </figure>
                    <div class='right'>
                      <h3><a href="property.html">1 Central Park S</a></h3>
                      <p>Las Vegas, NV</p>
                      <div class='description'>
                        <p>Aliquam luctus, metus eu hendrerit bibendum, justo orci pulvinar enim, sed euismod risus tellus eu mi. Vivamus accumsan adipiscing leo quis suscipit. In hac habitasse platea dictumst.</p>
                      </div>
                      <div class='price-wrapper'>
                        <div class='price'>$1,499</div>
                        <div class='rate'>/month</div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
              <div class='bottom'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <p>4 beds  +  2 baths  +  245 sqft</p>
                    <div class='star-rating'>
                      <button class='star active'>1 Star</button>
                      <button class='star active'>2 Star</button>
                      <button class='star active'>3 Star</button>
                      <button class='star active'>4 Star</button>
                      <button class='star active'>5 Star</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class='featured-item featured-list'>
              <div class='top'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <figure>
                      <img src="img/photos/4834197589_84d75a42bd_b.jpg" alt="" />
                      <div class='banner'>For Sale</div>
                      <a href="property.html" class='figure-hover'>Zoom</a>
                    </figure>
                    <div class='right'>
                      <h3><a href="property.html">555 Malcolm X Blvd</a></h3>
                      <p>Los Angeles, CA</p>
                      <div class='description'>
                        <p>Aliquam luctus, metus eu hendrerit bibendum, justo orci pulvinar enim, sed euismod risus tellus eu mi. Vivamus accumsan adipiscing leo quis suscipit. In hac habitasse platea dictumst.</p>
                      </div>
                      <div class='price-wrapper'>
                        <div class='price'>$11,000</div>
                        <div class='rate'>/year</div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
              <div class='bottom'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <p>4 beds  +  2 baths  +  245 sqft</p>
                    <div class='star-rating'>
                      <button class='star active'>1 Star</button>
                      <button class='star active'>2 Star</button>
                      <button class='star active'>3 Star</button>
                      <button class='star active'>4 Star</button>
                      <button class='star active'>5 Star</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class='featured-item featured-list'>
              <div class='top'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <figure>
                      <img src="img/photos/4834201025_e7f66118eb_b.jpg" alt="" />
                      <div class='banner'>For Sale</div>
                      <a href="property.html" class='figure-hover'>Zoom</a>
                    </figure>
                    <div class='right'>
                      <h3><a href="property.html">520 W 110th St</a></h3>
                      <p>Las Vegas, NV</p>
                      <div class='description'>
                        <p>Aliquam luctus, metus eu hendrerit bibendum, justo orci pulvinar enim, sed euismod risus tellus eu mi. Vivamus accumsan adipiscing leo quis suscipit. In hac habitasse platea dictumst.</p>
                      </div>
                      <div class='price-wrapper'>
                        <div class='price'>$14,100</div>
                        <div class='rate'>/year</div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
              <div class='bottom'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <p>4 beds  +  2 baths  +  245 sqft</p>
                    <div class='star-rating'>
                      <button class='star active'>1 Star</button>
                      <button class='star active'>2 Star</button>
                      <button class='star active'>3 Star</button>
                      <button class='star active'>4 Star</button>
                      <button class='star active'>5 Star</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class='featured-item featured-list'>
              <div class='top'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <figure>
                      <img src="img/photos/4834203945_3e56a09048_b.jpg" alt="" />
                      <div class='banner'>For Sale</div>
                      <a href="property.html" class='figure-hover'>Zoom</a>
                    </figure>
                    <div class='right'>
                      <h3><a href="property.html">100 W 57th St</a></h3>
                      <p>Los Angeles, CA</p>
                      <div class='description'>
                        <p>Aliquam luctus, metus eu hendrerit bibendum, justo orci pulvinar enim, sed euismod risus tellus eu mi. Vivamus accumsan adipiscing leo quis suscipit. In hac habitasse platea dictumst.</p>
                      </div>
                      <div class='price-wrapper'>
                        <div class='price'>$12,300</div>
                        <div class='rate'>/year</div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
              <div class='bottom'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <p>4 beds  +  2 baths  +  245 sqft</p>
                    <div class='star-rating'>
                      <button class='star active'>1 Star</button>
                      <button class='star active'>2 Star</button>
                      <button class='star active'>3 Star</button>
                      <button class='star active'>4 Star</button>
                      <button class='star active'>5 Star</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class='featured-item featured-list'>
              <div class='top'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <figure>
                      <img src="img/photos/4834790926_0228ed6cde_b.jpg" alt="" />
                      <div class='banner'>For Sale</div>
                      <a href="property.html" class='figure-hover'>Zoom</a>
                    </figure>
                    <div class='right'>
                      <h3><a href="property.html">140 E 63rd St</a></h3>
                      <p>Boston, MA</p>
                      <div class='description'>
                        <p>Aliquam luctus, metus eu hendrerit bibendum, justo orci pulvinar enim, sed euismod risus tellus eu mi. Vivamus accumsan adipiscing leo quis suscipit. In hac habitasse platea dictumst.</p>
                      </div>
                      <div class='price-wrapper'>
                        <div class='price'>$1,099</div>
                        <div class='rate'>/month</div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
              <div class='bottom'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <p>4 beds  +  2 baths  +  245 sqft</p>
                    <div class='star-rating'>
                      <button class='star active'>1 Star</button>
                      <button class='star active'>2 Star</button>
                      <button class='star active'>3 Star</button>
                      <button class='star active'>4 Star</button>
                      <button class='star active'>5 Star</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class='featured-item featured-list'>
              <div class='top'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <figure>
                      <img src="img/photos/4834812234_3379989227_b.jpg" alt="" />
                      <div class='banner'>For Sale</div>
                      <a href="property.html" class='figure-hover'>Zoom</a>
                    </figure>
                    <div class='right'>
                      <h3><a href="property.html">161 E 110th St</a></h3>
                      <p>Los Angeles, CA</p>
                      <div class='description'>
                        <p>Aliquam luctus, metus eu hendrerit bibendum, justo orci pulvinar enim, sed euismod risus tellus eu mi. Vivamus accumsan adipiscing leo quis suscipit. In hac habitasse platea dictumst.</p>
                      </div>
                      <div class='price-wrapper'>
                        <div class='price'>$19,499</div>
                        <div class='rate'>/year</div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
              <div class='bottom'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <p>4 beds  +  2 baths  +  245 sqft</p>
                    <div class='star-rating'>
                      <button class='star active'>1 Star</button>
                      <button class='star active'>2 Star</button>
                      <button class='star active'>3 Star</button>
                      <button class='star active'>4 Star</button>
                      <button class='star active'>5 Star</button>
                    </div>
                  </div>
                </div>
              </div>
            </div><div class='featured-item featured-list'>
              <div class='top'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <figure>
                      <img src="img/photos/4834826842_cdeb5bc8be_b.jpg" alt="" />
                      <div class='banner'>For Sale</div>
                      <a href="property.html" class='figure-hover'>Zoom</a>
                    </figure>
                    <div class='right'>
                      <h3><a href="property.html">East 61st Street and Park Avenue</a></h3>
                      <p>Los Angeles, CA</p>
                      <div class='description'>
                        <p>Aliquam luctus, metus eu hendrerit bibendum, justo orci pulvinar enim, sed euismod risus tellus eu mi. Vivamus accumsan adipiscing leo quis suscipit. In hac habitasse platea dictumst.</p>
                      </div>
                      <div class='price-wrapper'>
                        <div class='price'>$12,500</div>
                        <div class='rate'>/year</div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
              <div class='bottom'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <p>4 beds  +  2 baths  +  245 sqft</p>
                    <div class='star-rating'>
                      <button class='star active'>1 Star</button>
                      <button class='star active'>2 Star</button>
                      <button class='star active'>3 Star</button>
                      <button class='star active'>4 Star</button>
                      <button class='star active'>5 Star</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
          <ul class="pagination pagination-sm">
            <li class='first-element'><a href="#">Prev</a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">...</a></li>
            <li><a href="#">48</a></li>
            <li><a href="#">49</a></li>
            <li class='last-element'><a href="#">Next</a></li>
          </ul>
          </div>
        </div>
      </section>
      <aside class='col-md-3'>
        <section class='widget'>
          <section class='widget-title uppercase'>
            <div class='inner'>
              <h2>Refine Search</h2>
            </div>
          </section>
          <section class='widget-content'>
            <form action="#">
              <div class='widget-section'>
                <div class='inner'>
                  <label for="location">Location</label>
                  <input type="text" name='location' id='location' class='input-block-level' value='Oxford'/>
                </div>
              </div>
              <div class='widget-section'>
                <div class='inner'>
                  <label for="propertyType">Property Type</label>
                  <select name="propertyType" id="propertyType" class='btn-block selectpicker'>
                    <option value="all">All</option>
                    <option value="all">Mansion</option>
                    <option value="all">Apartment</option>
                  </select>
                </div>
              </div>
              <div class='widget-section'>
                <div class='inner'>
                  <label for="category">Category</label>
                  <select name="propertyType" id="category" class='btn-block selectpicker'>
                    <option value="all">For Sale</option>
                    <option value="all">For Rent</option>
                    <option value="all">Forclosures</option>
                  </select>
                </div>
              </div>
              <div class='widget-section first-half'>
                <div class='inner'>
                  <label for="minPrice">Min. Price</label>
                  <select name="propertyType" id="minPrice" class='btn-block selectpicker'>
                    <option value="all">$17K</option>
                    <option value="all">$27K</option>
                    <option value="all">$37K</option>
                  </select>
                </div>
              </div>
              <div class='widget-section second-half'>
                <div class='inner'>
                  <label for="maxPrice">Max. Price</label>
                  <select name="propertyType" id="maxPrice" class='btn-block selectpicker'>
                    <option value="all">$999K</option>
                    <option value="all">$899K</option>
                    <option value="all">$799K</option>
                  </select>
                </div>
              </div>
              <div class='widget-section'>
                <div class='inner'>
                  <label for="bedrooms">Bedrooms</label>
                  <select name="propertyType" id="bedrooms" class='btn-block selectpicker'>
                    <option value="all">3</option>
                    <option value="all">2</option>
                    <option value="all">4</option>
                    <option value="all">5</option>
                  </select>
                </div>
              </div>
              <div class='widget-section'>
                <div class='inner' style='position: relative;'>
                  <label for="size">Size</label>
                  <input type="text" name='size' id='size' class='input-block-level' value='500'/>
                  <span class='measure-type'>sqft</span>
                </div>
              </div>
              <div class='widget-section'>
                <div class='inner'>
                  <label for='range'>Slide Example</label>
                  <input type="text" name='size' id='range' class='input-block-level range-example'/>
                </div>
              </div>
              <section class='widget-buttons'>
                <div class='inner'>
                  <a href="#" class='more-options'>More Options</a> <br />
                  <a href='#' class='btn btn-primary btn-large btn-block'>Update</a>
                </div>
              </section>
            </form>
          </section>
          <a href="#" id='clearFilters'>Clear all filters</a>
        </section>
      </aside>
    </section>
  </section>
</section>
<section id='contact-form'>
  <section class='container'>
    <section class='row'>
      <div class='col-md-9'>
        <div class='contact-box'>
          <div class='title-bar'>
            <div class='inner'>
              <h2>Contact relevant estate agents & new homes developers</h2>
              <p>Send a message to agents and developers matching your search for in using the box below.</p>
            </div>
          </div>
          <div class='contact-box-content'>
            <div class='inner'>
              <div class='half first-half'>
                <form action="#">
                  <label for="contact-name">Your Name</label>
                  <input type="text" name='contact-name' placeholder="John Smith" id='contact-name' class='input-block-level'/>
                  <label for="contact-message">Your Message</label>
                  <textarea name="contact-message" id="contact-message" class='input-block-level' rows="10" placeholder="Your message"></textarea>
                  <label for="contact-phone">Your Phone</label>
                  <input type="tel" name='contact-phone' placeholder="(XXX) XXX - XX - XX" id='contact-phone' class='input-block-level'/>
                  <label for="contact-email">Your Email</label>
                  <input type="email" name='contact-email' placeholder="example@example.com" id='contact-email' class='input-block-level'/>
                  <label class="checkbox">
                    <input type="checkbox"> Keep me informed on property market updates
                  </label>
                </form>
              </div>
              <div class='half'>
                <div class='custom-multiple-select-filters'>
                  <span>Select: </span>
                  <ul>
                    <li><a href="#" class='all'>All</a></li>
                    <li>|</li>
                    <li><a href="#" class='featured'>Featured</a></li>
                    <li>|</li>
                    <li><a href="#" class='none'>None</a></li>
                  </ul>
                </div>
                <div class='custom-multiple-select'>
                  <select multiple='multiple'>
                    <option rel='1' value="1">Hello 1</option>
                    <option rel='2' value="2">Hello 2</option>
                    <option rel='3' value="3">Hello 3</option>
                    <option rel='4' value="4">Hello 4</option>
                    <option rel='5' value="5">Hello 5</option>
                    <option rel='6' value="6">Hello 6</option>
                    <option rel='7' value="7">Hello 7</option>
                    <option rel='8' value="8">Hello 8</option>
                  </select>
                  <ul>
                    <li rel='1' class='featured'>
                      <div class='inner-list'>
                        <strong>Andrews - Cowley, OX4</strong> <br />
                        <span>01865 360070</span>
                      </div>
                    </li>
                    <li rel='2'>
                      <div class='inner-list'>
                        <strong>Andrews - Cowley, OX4</strong> <br />
                        <span>01865 360070</span>
                      </div>
                    </li>
                    <li rel='3' class='featured'>
                      <div class='inner-list'>
                        <strong>Andrews - Cowley, OX4</strong> <br />
                        <span>01865 360070</span>
                      </div>
                    </li>
                    <li rel='4'>
                      <div class='inner-list'>
                        <strong>Andrews - Cowley, OX4</strong> <br />
                        <span>01865 360070</span>
                      </div>
                    </li>
                    <li rel='5' class='featured'>
                      <div class='inner-list'>
                        <strong>Andrews - Cowley, OX4</strong> <br />
                        <span>01865 360070</span>
                      </div>
                    </li>
                    <li rel='6' class='featured'>
                      <div class='inner-list'>
                        <strong>Andrews - Cowley, OX4</strong> <br />
                        <span>01865 360070</span>
                      </div>
                    </li>
                    <li rel='7'>
                      <div class='inner-list'>
                        <strong>Andrews - Cowley, OX4</strong> <br />
                        <span>01865 360070</span>
                      </div>
                    </li>
                    <li rel='8'>
                      <div class='inner-list'>
                        <strong>Andrews - Cowley, OX4</strong> <br />
                        <span>01865 360070</span>
                      </div>
                    </li>
                  </ul>
                </div>
                <input type="submit" class='btn btn-primary btn-large pull-right' value='Send Message'/>
              </div>
            </div>
          </div>
        </div>
      </div>
      <aside class='col-md-3'>
        <section class='widget'>
          <section class='widget-title'>
            <div class='inner'>
              <h2>Text Widget</h2>
            </div>
          </section>
          <section class='widget-content top-arrow'>
            <div class='inner'>
              <p>Vestibulum venenatis sem a ligula rhoncus et gravida lacus consequat. Praesent sollicitudin dolor euismod quam elementum a lacinia odio vehicula.</p>
            </div>
          </section>
        </section>
        <section class='widget'>
          <section class='widget-title'>
            <div class='inner'>
              <h2>Useful Links</h2>
            </div>
          </section>
          <section class='widget-content top-arrow'>
            <ul class='widget-list'>
              <li><a href="#">Link Example</a></li>
              <li><a href="#">Link Example</a></li>
              <li><a href="#">Link Example</a></li>
              <li><a href="#">Link Example</a></li>
            </ul>
          </section>
        </section>
      </aside>
    </section>
  </section>
</section>