<section id='content'>
  <section class='container'>
    <section class='row featured-items'>
    <aside class='col-md-3'>
        <section class='widget'>
            <section class='widget-title uppercase'>
                <div class='inner'>
                    <h2>Kategorie Ogłoszeń</h2>
                </div>
            </section>
            <section class='widget-content'>
                <ul>
                    <?php foreach($this->categories as $category): ?>
                           <li><a href="<?= $this->url('advert/sublist', array('id' => $category->getId(), 'url' => $category->getUrl())) ?>"><?= $category->getName(); ?></a></li>
                           <?php if(in_array($category->getId(), $this->category_ids)): ?>
                                <ul>
                                    <?php foreach($this->subcategories as $sub): ?>
                                        <li><a href="<?= $this->url('advert/sublist', array('id' => $sub->getId(), 'url' => $sub->getUrl())) ?>"><?= $sub->getName(); ?></a></li>
                                    <?php endforeach; ?>
                                </ul>
                            <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
                <form action="#">
                    <div class='widget-section'>
                        <div class='inner'>
                            <label for="location">Location</label>
                            <input type="text" name='location' id='location' class='input-block-level' value='Oxford'/>
                        </div>
                    </div>
                    <div class='widget-section'>
                        <div class='inner'>
                            <label for="propertyType">Property Type</label>
                            <select name="propertyType" id="propertyType" class='btn-block selectpicker'>
                                <option value="all">All</option>
                                <option value="all">Mansion</option>
                                <option value="all">Apartment</option>
                            </select>
                        </div>
                    </div>
                    <div class='widget-section'>
                        <div class='inner'>
                            <label for="category">Category</label>
                            <select name="propertyType" id="category" class='btn-block selectpicker'>
                                <option value="all">For Sale</option>
                                <option value="all">For Rent</option>
                                <option value="all">Forclosures</option>
                            </select>
                        </div>
                    </div>
                    <div class='widget-section first-half'>
                        <div class='inner'>
                            <label for="minPrice">Min. Price</label>
                            <select name="propertyType" id="minPrice" class='btn-block selectpicker'>
                                <option value="all">$17K</option>
                                <option value="all">$27K</option>
                                <option value="all">$37K</option>
                            </select>
                        </div>
                    </div>
                    <div class='widget-section second-half'>
                        <div class='inner'>
                            <label for="maxPrice">Max. Price</label>
                            <select name="propertyType" id="maxPrice" class='btn-block selectpicker'>
                                <option value="all">$999K</option>
                                <option value="all">$899K</option>
                                <option value="all">$799K</option>
                            </select>
                        </div>
                    </div>
                    <div class='widget-section'>
                        <div class='inner'>
                            <label for="bedrooms">Bedrooms</label>
                            <select name="propertyType" id="bedrooms" class='btn-block selectpicker'>
                                <option value="all">3</option>
                                <option value="all">2</option>
                                <option value="all">4</option>
                                <option value="all">5</option>
                            </select>
                        </div>
                    </div>
                    <div class='widget-section'>
                        <div class='inner' style='position: relative;'>
                            <label for="size">Size</label>
                            <input type="text" name='size' id='size' class='input-block-level' value='500'/>
                            <span class='measure-type'>sqft</span>
                        </div>
                    </div>
                    <div class='widget-section'>
                        <div class='inner'>
                            <label for='range'>Slide Example</label>
                            <input type="text" name='size' id='range' class='input-block-level range-example'/>
                        </div>
                    </div>
                    <section class='widget-buttons'>
                        <div class='inner'>
                            <a href="#" class='more-options'>More Options</a> <br />
                            <a href='#' class='btn btn-primary btn-large btn-block'>Update</a>
                        </div>
                    </section>
                </form>
            </section>
            <a href="#" id='clearFilters'>Clear all filters</a>
        </section>
    </aside>
      <section class='col-md-9'>
        <div class='row'>
          <div class='col-md-12'>
            <div class='top-bar'>
              <div class='bar-title'>
                <div class='inner'>
                  <div class='pull-left custom-margin'>
                    <strong>1</strong> - <strong>9</strong> of <strong>1,075</strong> results for <strong>Oxford</strong> property <strong>For Sale</strong>
                  </div>
                  <div class='pull-right results-per-page custom-margin'>
                    <span class='text-line'>Results per page:</span>
                    <ul>
                      <li class='active'><a href="#">9</a></li>
                      <li>|</li>
                      <li><a href="#">18</a></li>
                      <li>|</li>
                      <li><a href="#">27</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class='bar-bottom'>
                <div class='inner'>
                  <div class='pull-left custom-margin'>
                    <span class='text-line'>Sort by:</span>
                    <select class='selectpicker'>
                      <option value="relevance">Relevance</option>
                      <option value="date">Date</option>
                    </select>
                  </div>
                  <div class='pull-right view-type custom-margin'>
                    <span class='text-line'>View:</span>
                    <ul>
                      <li><a href="search-grid.html" class='grid'>Grid</a></li>
                      <li class='active'><a href="search-list.html" class='list'>List</a></li>
                      <li class='last-element'><a href="search-location.html" class='location'>Location</a></li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
            <div class='col-md-12'>
                <h2>Ogłoszenia Specjalne</h2>
                <div class='featured-items-slider'>
                    <ul class='slides'>
                        <li>
                            <div class='row'>
                                <div class='col-md-4 featured-item-wrapper'>
                                    <div class='featured-item'>
                                        <div class='top'>
                                            <div class='inner-border'>
                                                <div class='inner-padding'>
                                                    <figure>
                                                        <img src="img/photos/4834197589_84d75a42bd_b.jpg" alt="" />
                                                        <div class='banner'>For Sale</div>
                                                        <a href="property.html" class='figure-hover'>Zoom</a>
                                                    </figure>
                                                    <h3><a href="property.html">555 Malcolm X Blvd</a></h3>
                                                    <p>Los Angeles, CA</p>
                                                </div>
                                            </div>
                                            <i class='bubble'></i>
                                        </div>
                                        <div class='bottom'>
                                            <div class='inner-border'>
                                                <div class='inner-padding'>
                                                    <p>3 beds  +  1 bath  +  100 sqft</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class='star-rating'>
                                        <button class='star blue'>1 Star</button>
                                        <button class='star active'>2 Star</button>
                                        <button class='star active'>3 Star</button>
                                        <button class='star'>4 Star</button>
                                        <button class='star'>5 Star</button>
                                    </div>
                                </div>
                                <div class='col-md-4 featured-item-wrapper'>
                                    <div class='featured-item'>
                                        <div class='top'>
                                            <div class='inner-border'>
                                                <div class='inner-padding'>
                                                    <figure>
                                                        <img src="img/photos/4834201025_e7f66118eb_b.jpg" alt="" />
                                                        <div class='banner'>For Rent</div>
                                                        <a href="property.html" class='figure-hover'>Zoom</a>
                                                    </figure>
                                                    <h3><a href="property.html">520 W 110th St</a></h3>
                                                    <p>Las Vegas, NV</p>
                                                </div>
                                            </div>
                                            <i class='bubble'></i>
                                        </div>
                                        <div class='bottom'>
                                            <div class='inner-border'>
                                                <div class='inner-padding'>
                                                    <p>4 beds  +  2 baths  +  245 sqft</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class='star-rating'>
                                        <button class='star active'>1 Star</button>
                                        <button class='star active'>2 Star</button>
                                        <button class='star active'>3 Star</button>
                                        <button class='star active'>4 Star</button>
                                        <button class='star active'>5 Star</button>
                                    </div>
                                    <div class='price-wrapper'>
                                        <div class='price'>$17,000</div>
                                        <div class='rate'>/year</div>
                                    </div>
                                </div>
                                <div class='col-md-4 featured-item-wrapper'>
                                    <div class='featured-item'>
                                        <div class='top'>
                                            <div class='inner-border'>
                                                <div class='inner-padding'>
                                                    <figure>
                                                        <img src="img/photos/4834203945_3e56a09048_b.jpg" alt="" />
                                                        <a href="property.html" class='figure-hover'>Zoom</a>
                                                    </figure>
                                                    <h3><a href="property.html">100 W 57th St</a></h3>
                                                    <p>Los Angeles, CA</p>
                                                </div>
                                            </div>
                                            <i class='bubble'></i>
                                        </div>
                                        <div class='bottom'>
                                            <div class='inner-border'>
                                                <div class='inner-padding'>
                                                    <p>2 beds  +  2 baths + 168 sqft</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class='star-rating'>
                                        <button class='star active'>1 Star</button>
                                        <button class='star active'>2 Star</button>
                                        <button class='star active'>3 Star</button>
                                        <button class='star active'>4 Star</button>
                                        <button class='star active'>5 Star</button>
                                    </div>
                                    <div class='price-wrapper'>
                                        <div class='price'>$3,400</div>
                                        <div class='rate'>/mo</div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class='row'>
          <div class='col-md-12 featured-item-list'>
            <?php foreach($this->adverts as $advert): ?>
                <div class='featured-item featured-list'>
              <div class='top'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <figure>
                      <img src="<?= $this->basePath().Advert\Entity\Image::IMAGE_PATH_VIEW.$advert->getUser_id().DIRECTORY_SEPARATOR.$advert->getImages()->get(0)->getName(); ?>" alt="" />
                      <div class='banner'><?= Advert\Entity\Advert::advertTypeArray($advert->getAdvertType()); ?></div>
                      <a href="<?= $this->url('advert/view', array('id' => $advert->getId(), 'url' => $advert->getUrl())); ?>" class='figure-hover'>Zoom</a>
                    </figure>
                    <div class='right'>
                      <h3><a href="<?= $this->url('advert/view', array('id' => $advert->getId(), 'url' => $advert->getUrl())); ?>"><?= $advert->getName() ?></a></h3>
                      <p>Las Vegas, NV</p>
                      <div class='description'>
                        <p><?= $advert->getDescription() ?></p>
                      </div>
                      <div class='price-wrapper'>
                        <div class='price'>PLN <?= $advert->getAmount() ?></div>
                        <div class='rate'>/month</div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
              <div class='bottom'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <p>4 beds  +  2 baths  +  245 sqft</p>
                    <div class='star-rating'>
                      <button class='star active'>1 Star</button>
                      <button class='star active'>2 Star</button>
                      <button class='star active'>3 Star</button>
                      <button class='star active'>4 Star</button>
                      <button class='star active'>5 Star</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <?php endforeach; ?>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
          <ul class="pagination pagination-sm">
            <li class='first-element'><a href="#">Prev</a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">...</a></li>
            <li><a href="#">48</a></li>
            <li><a href="#">49</a></li>
            <li class='last-element'><a href="#">Next</a></li>
          </ul>
          </div>
        </div>
      </section>
    </section>
  </section>
</section>