<?php
    $layout = new \Application\Components\Helper\LayoutHelper();
    $layout->setFormArray($this->query);
?>
<section id='content'>
  <section class='container'>
    <section class='row featured-items'>
    <aside class='col-md-3'>
        <section class='widget'>
            <section class='widget-title uppercase'>
                <div class='inner'>
                    <div class="pull-left mar-10-auto">
                        <strong>Ogłoszenia</strong>
                    </div>
                </div>
            </section>
            <section class='widget-content'>
                <form id="search_advert" method="GET">
                    <div class='widget-section'>
                        <div class='inner'>
                            <div class="form-group">
                                <label for="search">Wyszukiwarka</label>
                                <input type="text" class="form-control" name="search" id="search" placeholder="Szukaj">
                            </div>
                        </div>
                    </div>
                    </form>
                    <form id="form_advert" method="GET">
                    <div class='widget-section'>
                        <div class='inner'>
                            <label for="propertyType">Kategorie</label>
                            <ul class="menulist category-tree-view">
                                <?php foreach($this->category as $category): ?>
                                    <li><a href="<?= $this->url('advert/sublist', array('id' => $category['id'], 'url' => $category['url'])) ?>"><?= $category['name']; ?> <span>(<?= $category['count']; ?>)</span></a></li>
                                    <?php if($this->currentCategory): ?>
                                        <?php if(isset($category['sub'])): ?>
                                            <ul class="submenulist">
                                                <?php foreach($category['sub'] as $sub): ?>
                                                    <li><a href="<?= $this->url('advert/sublist', array('id' => $sub['id'], 'url' => $sub['url'])) ?>"><?= $sub['name']; ?> <span>(<?= $sub['count']; ?>)</span></a></li>
                                                    <?php if(isset($sub['sub'])): ?>
                                                        <ul class="submenulist">
                                                            <?php foreach($sub['sub'] as $subLev): ?>
                                                                <li><a href="<?= $this->url('advert/sublist', array('id' => $subLev['id'], 'url' => $subLev['url'])) ?>"><?= $subLev['name']; ?> <span>(<?= $subLev['count']; ?>)</span></a></li>
                                                            <?php endforeach; ?>
                                                        </ul>
                                                    <?php endif; ?>
                                                <?php endforeach; ?>
                                            </ul>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                    <div class='widget-section'>
                        <div class='inner'>
                            <div class="form-group">
                                <label for="advert_type">Rodzaj Ogłoszenia</label>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="advert_type" value="1"  checked>
                                        Kupię
                                    </label>
                                </div>
                                <div class="radio">
                                    <label>
                                        <input type="radio" name="advert_type" value="2">
                                        Sprzedam
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class='widget-section'>
                        <div class='inner'>
                            <div class="form-group">
                                <label for="pieces">Ilość</label>
                                <div class="col-sm-12 padding-0 mar-bottom15">
                                    <div class="col-sm-6 padding-0" style="padding-right: 2px;">
                                        <input type="text" name='pieces_min' class="form-control" value="<?= $layout->getFormParam('pieces_min'); ?>" />
                                    </div>
                                    <div class="col-sm-6 padding-0" style="padding-left: 2px;">
                                        <input type="text" name='pieces_max' class="form-control" value="<?= $layout->getFormParam('pieces_max'); ?>" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class='widget-section'>
                        <div class='inner'>
                            <div class="form-group">
                                <label for="advert_type">Lokalizacja</label>
                                <div class="col-sm-12 padding-0 mar-bottom15">
                                    <div class="col-sm-12 padding-0">
                                        <input type="text" name='district' id='district' placeholder="Województwo" value="<?= $layout->getFormParam('district'); ?>" class="form-control" />
                                    </div>
                                    <div class="col-sm-12 padding-0 mar-top5">
                                        <input type="text" name='city' id='city' placeholder="Miejscowość" value="<?= $layout->getFormParam('city'); ?>" class="form-control col-lg-5"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class='widget-section'>
                        <div class='inner'>
                            <div class="form-group">
                                <label for="advert_type">Cena</label>
                                <div class="col-sm-12 padding-0 mar-bottom15">
                                <div class="col-sm-6 padding-0" style="padding-right: 2px;">
                                    <input type="text" name='amount_min' id='amount_min' class="form-control" value="<?= $layout->getFormParam('amount_min'); ?>" />
                                    </div>
                                <div class="col-sm-6 padding-0" style="padding-left: 2px;">
                                    <input type="text" name='amount_max' id='amount_max' class="form-control" value="<?= $layout->getFormParam('amount_max'); ?>"/>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <section class='widget-buttons'>
                        <div class='inner'>
                            <input id="sortInput" type="hidden" name="sort" />
                            <input id="resultsInput" type="hidden" name="results" value="20" />
                            <button class="btn btn-default btn-primary" type="submit">Szukaj Ofert</button>
                        </div>
                    </section>
                </form>
            </section>
        </section>
    </aside>
      <section class='col-md-9'>
        <div class='row'>
          <div class='col-md-12'>
            <div class='top-bar'>
              <div class='bar-title'>
                <div class='inner'>
                  <div class='pull-left custom-margin'>
                    <strong><?= ($this->resultPage * $this->currentPage) - $this->resultPage + 1; ?></strong> - <strong><?= ($this->currentPage * $this->resultPage) < $this->resultCount ? ($this->currentPage * $this->resultPage) : $this->resultCount; ?></strong> z <strong><?= $this->resultCount ?></strong> wyników
                  </div>
                  <div class='pull-right results-per-page custom-margin'>
                    <span class='text-line'>Wyników na stronie:</span>
                    <ul id="resultPage">
                      <li <?= $layout->getFormParamEquals('results', '40', "class='active'", "class='active'"); ?>><a href="#">20</a></li>
                      <li>|</li>
                      <li <?= $layout->getFormParamEquals('results', '40', "class='active'"); ?>><a href="#">40</a></li>
                      <li>|</li>
                      <li <?= $layout->getFormParamEquals('results', '60', "class='active'"); ?>><a href="#">60</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class='bar-bottom'>
                <div class='inner'>
                  <div class='pull-left custom-margin sortbox'>
                    <span class='text-line'>Sortowanie:</span>
                    <select class="selectpicker sortpicker" name="sort">
                        <option data-subtext="od najniższej" value="sort_amount_asc" <?= $layout->getFormParamEquals('sort', 'sort_amount_asc'); ?>>Cena</option>
                        <option data-subtext="od najwyższej" value="sort_amount_desc" <?= $layout->getFormParamEquals('sort', 'sort_amount_desc'); ?>>Cena</option>
                        <option data-divider="true"></option>
                        <option data-subtext="najmniej" value="sort_created_at_desc" <?= $layout->getFormParamEquals('sort', 'sort_created_at_desc'); ?>>Data zakończenia</option>
                        <option data-subtext="najwięcej" value="sort_created_at_asc" <?= $layout->getFormParamEquals('sort', 'sort_created_at_asc'); ?>>Data zakończenia</option>
                        <option data-divider="true"></option>
                        <option data-subtext="od najczęstrzych" value="sort_visits_desc" <?= $layout->getFormParamEquals('sort', 'sort_visits_desc'); ?>>Oglądnięte</option>
                        <option data-subtext="od najrzadszych" value="sort_visits_asc" <?= $layout->getFormParamEquals('sort', 'sort_visits_asc'); ?>>Oglądnięte</option>
                    </select>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class='row'>
          <div class='col-md-12 featured-item-list'>
            <?php foreach($this->adverts as $advert): ?>
                <div class='featured-item featured-list'>
              <div class='top'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                    <figure>
                      <img src="<?= $this->basePath().Advert\Entity\Image::IMAGE_PATH_VIEW.$advert->getCompanyId().DIRECTORY_SEPARATOR . '90x160' . DIRECTORY_SEPARATOR .$advert->getImages()->get(0)->getName(); ?>" alt="" />
                      <div class='banner'><?= Advert\Entity\Advert::advertTypeArray($advert->getAdvertType()); ?></div>
                      <a href="<?= $this->url('advert/view', array('id' => $advert->getId(), 'url' => $advert->getUrl())); ?>" class='figure-hover'>Zoom</a>
                    </figure>
                    <div class='right'>
                      <h3><a href="<?= $this->url('advert/view', array('id' => $advert->getId(), 'url' => $advert->getUrl())); ?>"><strong><?= strlen($advert->getName()) > 51 ? substr($advert->getName(), 0, 50).'...' : $advert->getName();  ?></strong></a></h3>
                        <?php $company = $this->getRepos('Company\Entity\Company')->find($advert->getCompanyId()); ?>
                      <p><?= $company->getCity(); ?>, <?= $company->getCountry(); ?></p>
                      <div class='description'>
                        <p><?= strlen(strip_tags($advert->getDescription())) > 180 ? substr(strip_tags($advert->getDescription()), 0, 150).'... <a class="link-blue" href="' . $this->url('advert/view', array('id' => $advert->getId(), 'url' => $advert->getUrl())) . '">[więcej]</a>' : strip_tags($advert->getDescription()); ?></p>
                      </div>
                      <div class='price-wrapper'>
                        <div class='price'>PLN <?= $advert->getAmount() ?></div>
                        <div class='rate'>/całość</div>
                      </div>
                    </div>
                  </div>
                </div>

              </div>
              <div class='bottom'>
                <div class='inner-border'>
                  <div class='inner-padding'>
                      <div class="pull-left bottom-advert">
                          <span>Data zakończenia: <span data-toggle="tooltip" data-placement="bottom" title="<?= $advert->getFinishedAt()->format('d-m-Y H:i:s'); ?>" class="<?php if($advert->isLessOneDay()): ?>red-color<?php endif; ?>"><?= $advert->getHoursToFinishAdvert(); ?></span></span>
                          <span class="space-line"> | </span>
                          <span>Oglądnięte: <?= $advert->getVisits(); ?></span>
                          <span class="space-line"> | </span>
                          <span>Kategoria: <a class="link-gray" href="<?= $this->url('advert/sublist', array('id' => $advert->getCategory()->getId(), 'url' => $advert->getCategory()->getUrl())) ?>"><?= $advert->getCategory()->getName(); ?></a></span>
                      </div>
                      <?= \Company\Entity\Company::rank($company->getRank(), ''); ?>
                  </div>
                </div>
              </div>
            </div>
            <?php endforeach; ?>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
              <?php $PagId = $this->currentCategory ? $this->currentCategory->getId() : null;  ?>
              <?php $PagUrl = $this->currentCategory ? $this->currentCategory->getUrl() : null;  ?>
              <?php if($this->pages > 1): ?>
                  <ul class="pagination pagination-sm pull-right">
                      <?php if($this->currentPage != 1): ?>
                          <li class='first-element'><a href="<?= $this->url('advert/sublist', array('id' => $PagId,'url' => $PagUrl, 'page' => $this->currentPage-1), array('query' => $this->query)); ?>">Prev</a></li>
                      <?php endif; ?>
                    <?php for($x = 1; $x <= $this->pages; $x++): ?>
                        <li <?php if($x == $this->currentPage): ?>class="active"<?php endif; ?>><a href="<?= $this->url('advert/sublist', array('id' => $PagId,'url' => $PagUrl, 'page' => $x), array('query' => $this->query)); ?>"><?= $x; ?></a></li>
                    <?php endfor; ?>
                      <?php if($this->currentPage != $this->pages): ?>
                          <li class='last-element'><a href="<?= $this->url('advert/sublist', array('id' => $PagId,'url' => $PagUrl, 'page' => $this->currentPage+1), array('query' => $this->query)); ?>">Next</a></li>
                      <?php endif; ?>
                  </ul>
              <?php endif; ?>
          </div>
        </div>
      </section>
    </section>
  </section>
</section>