<section role="main" id="main">
  <section class="container">
    <section class="row featured-items ">
      <?= $this->partial('advert/advert/partial/menu.phtml'); ?>

      <div class="col-md-9">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Dashboard</h3>
          </div>
          <div class="panel-body">
            
          </div>
        </div>
      </div>
    </section>
  </section>
</section>