<?php
$layout = new \Application\Components\Helper\LayoutHelper();
$layout->setFormArray($this->query);
?>
<section role="main" id="main">
    <section class="container">
        <section class="row featured-items">

            <div class="flash-messages">
                <div class="alert alert-warning text-center">
                    <p>Nie możesz korzystać z wybrane pakietu. Pakiet jest <strong><abbr
                                title="Przejdź do zakładki Płatności aby w szybki sposób móc aktywować usługę.">Nieaktywny</abbr></strong>.
                        Opłać pakiet by móc w pełni korzystać z funkcjonalności serwisu.</p>
                </div>
            </div>
            <div class="toolbar">
                <ol class="breadcrumb">
                    <li class="home"><a href="/"><i class="fa fa-home"></i><span> Home</span></a></li>
                    <li class="active"><a href="/user/login" class=" active">Firma</a></li>
                    <li class="active"><a href="/user/profile" class=" active">Zarządzanie Ogłoszeniami</a></li>
                </ol>
            </div>
            <div class="wrapper">
                <div class="primary">
                    <section class="module">
                        <div class="ibox">
                            <div class="ibox-title">
                                <h5>Lista moich ogłoszeń</h5>

                                <div class="ibox-tools">
                                    <button type="button" link="<?= $this->url('advert/add'); ?>"
                                            class="buttonPoint btn btn-primary btn-xs pull-right">Dodaj Ogłoszenie
                                    </button>
                                </div>
                            </div>
                            <div class="ibox-content">
                                <div class="row m-b-sm m-t-sm mar-bottom15">
                                    <div class="col-md-1">
                                        <select class="selectpicker sortpicker" name="sort">
                                            <option data-subtext="od najniższej"
                                                    value="sort_amount_asc" <?= $layout->getFormParamEquals('sort', 'sort_amount_asc'); ?>>
                                                Cena
                                            </option>
                                            <option data-subtext="od najwyższej"
                                                    value="sort_amount_desc" <?= $layout->getFormParamEquals('sort', 'sort_amount_desc'); ?>>
                                                Cena
                                            </option>
                                            <option data-divider="true"></option>
                                            <option data-subtext="najmniej"
                                                    value="sort_created_at_desc" <?= $layout->getFormParamEquals('sort', 'sort_created_at_desc'); ?>>
                                                Data zakończenia
                                            </option>
                                            <option data-subtext="najwięcej"
                                                    value="sort_created_at_asc" <?= $layout->getFormParamEquals('sort', 'sort_created_at_asc'); ?>>
                                                Data zakończenia
                                            </option>
                                            <option data-divider="true"></option>
                                            <option data-subtext="od najczęstrzych"
                                                    value="sort_visits_desc" <?= $layout->getFormParamEquals('sort', 'sort_visits_desc'); ?>>
                                                Oglądnięte
                                            </option>
                                            <option data-subtext="od najrzadszych"
                                                    value="sort_visits_asc" <?= $layout->getFormParamEquals('sort', 'sort_visits_asc'); ?>>
                                                Oglądnięte
                                            </option>
                                        </select>
                                    </div>
                                    <div class="col-md-3 pull-right">
                                        <div class="input-group">
                                            <input type="text" class="input-sm form-control">
                                            <span class="input-group-btn">
                                                    <button class="btn btn-sm btn-primary" type="button">Szukaj</button>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                                <div class="project-list">
                                    <?php if (!$this->adverts): ?>
                                        <div class="alert alert-info text-center info-message-content mar-top15 mar-bottom15">
                                            <p>Obecnie nie posiadasz żadnego ogłoszenia.</p>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($this->alert): ?>
                                        <div class="alert alert-<?= $this->alert['alert']; ?> text-center info-message-content mar-top15 mar-bottom15">
                                            <p><?= $this->alert['message']; ?></p>
                                        </div>
                                    <?php endif; ?>

                                    <table class="table table-hover">
                                        <tbody>
                                        <?php foreach ($this->adverts as $advert): ?>
                                            <tr>
                                                <td class="project-status">
                                                    <?php $activeType = \Advert\Entity\Advert::getActiveType($advert->getActive()); ?>
                                                    <span class="label label-<?= $activeType->label; ?>"><?= $activeType->name; ?></span>
                                                </td>
                                                <td class="project-title">
                                                    <a href="<?= $this->url('advert/view', array('id' => $advert->getId(), 'url' => $advert->getUrl())); ?>"><img
                                                            class="img-circle pull-left" alt=""
                                                            src="<?= $this->basePath() . Advert\Entity\Image::IMAGE_PATH_VIEW . $advert->getCompanyId() . DIRECTORY_SEPARATOR . $advert->getImages()->get(0)->getName(); ?>"></a>

                                                    <div class="mar-left10 pull-left">
                                                        <a href="<?= $this->url('advert/view', array('id' => $advert->getId(), 'url' => $advert->getUrl())); ?>"><?= $advert->getName(); ?></a>
                                                        <br>

                                                        <div class="small-info">
                                                            <small>Data zakończenia: <span
                                                                    class="<?php if ($advert->isLessOneDay()): ?>red-color<?php endif; ?>"><?= $advert->getHoursToFinishAdvert(); ?></span>
                                                            </small>
                                                            <small class="space-line"> |</small>
                                                            <small>Oglądnięte: <?= $advert->getVisits(); ?></small>
                                                            <small class="space-line"> |</small>
                                                            <small>Ofert: <?= $advert->getVisits(); ?></small>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td class="project-completion">
                                                    <small class="first-amount">Poczatkowa Kwota:
                                                        PLN <?= $advert->getAmount(); ?></small>
                                                    <br/>
                                                    <small class="second-amount">Najwyższa Kwota:
                                                        PLN <?= $advert->getAmount() + 200; ?></small>
                                                </td>
                                                <td class="project-people">

                                                </td>
                                                <td class="project-actions">
                                                    <?php if($advert->getActive() == \Advert\Entity\Advert::ADVERT_FINISH): ?>
                                                        <a href="<?= $this->url('advert/edit', array('id' => $advert->getId())) ?>"
                                                           class="btn btn-primary btn-xs pull-right">Transakcja</a>
                                                    <?php else: ?>
                                                        <a href="<?= $this->url('advert/delete', array('id' => $advert->getId())) ?>"
                                                           type="button" class="btn btn-xs btn-danger mar-left5 pull-right" <?php if($advert->isLessThen(3)): ?>disabled<?php endif; ?>>Usuń</a>
                                                        <a href="<?= $this->url('advert/edit', array('id' => $advert->getId())) ?>"
                                                           class="btn btn-white btn-xs pull-right" <?php if($advert->isLessThen(3)): ?>disabled<?php endif; ?>>Edytuj</a>
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="ibox">
                            <div class="ibox-title">
                                <h5>Lista ogłoszeń w których bierzesz udział</h5>

                                <div class="ibox-tools">
                                    <button type="button" link="<?= $this->url('advert'); ?>"
                                            class="buttonPoint btn btn-primary btn-xs pull-right">Ogłoszenia
                                    </button>
                                </div>
                            </div>
                            <div class="ibox-content">

                                <div class="project-list">
                                    <?php if ($this->adverts): ?>
                                        <div
                                            class="alert alert-info text-center info-message-content mar-top15 mar-bottom15">
                                            <p>Obecnie nie posiadasz żadnego ogłoszenia.</p>
                                        </div>
                                    <?php endif; ?>

                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <aside class="secondary">
                    <section class="module module-narrow module-shallow">
                        <?= $this->partial('advert/advert/partial/advert.phtml'); ?>
                    </section>
                </aside>
            </div>
        </section>
    </section>
</section>