<section role="main" id="main">
    <section class="container">
        <section class="row featured-items">

            <div class="toolbar">
                <ol class="breadcrumb">
                    <li class="home"><a href="<?= $this->url('home'); ?>"><i class="fa fa-home"></i><span> Home</span> Home</a></li>
                    <li class="active"><a href="<?= $this->url('site'); ?>" class=" active">Strona Firmowa</a></li>
                </ol>
            </div>
            <div class="wrapper">
                <div class="primary">
                    <section class="module">
                        <div class="module-content">

                        </div>
                    </section>
                </div>
                <aside class="secondary">
                    <section class="module module-narrow module-shallow">
                        <h2 class="module-heading">Informacje</h2>
                        <div class="module-content">

                        </div>
                    </section>
                </aside>
            </div>
        </section>
    </section>
</section>
