<section role="main" id="main">
    <div class="carousel fade-carousel slide" data-ride="carousel" data-interval="4000" id="bs-carousel">
        <!-- Overlay -->
        <div class="overlay"></div>

        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#bs-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#bs-carousel" data-slide-to="1"></li>
            <li data-target="#bs-carousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item slides active">
                <div class="slide-1"></div>
                <div class="hero">
                    <hgroup>
                        <h1>We are creative</h1>

                        <h3>Get start your next awesome project</h3>
                    </hgroup>
                </div>
            </div>
            <div class="item slides">
                <div class="slide-2"></div>
                <div class="hero">
                    <hgroup>
                        <h1>We are smart</h1>

                        <h3>Get start your next awesome project</h3>
                    </hgroup>
                </div>
            </div>
            <div class="item slides">
                <div class="slide-3"></div>
                <div class="hero">
                    <hgroup>
                        <h1>We are amazing</h1>

                        <h3>Get start your next awesome project</h3>
                    </hgroup>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
        <div class="row">
            <div class="col-lg-12">
                <div class="col-xs-12 col-sm-4">
                    <figure>
                        <img class="img-circle img-responsive" alt="" src="http://placehold.it/300x300">
                    </figure>
                </div>

                <div class="col-xs-12 col-sm-8">
                    asasdasd
                </div>
            </div>
            <div class="col-lg-12">
                <div class="col-xs-12 col-sm-8">
                    asasdasd
                </div>

                <div class="col-xs-12 col-sm-4">
                    <figure>
                        <img class="img-circle img-responsive" alt="" src="http://placehold.it/300x300">
                    </figure>
                </div>
            </div>
        </div>
    </div>


    <div class="col-md-12" data-wow-delay="0.2s">
        <div class="carousel slide" data-ride="carousel" id="quote-carousel">
            <!-- Bottom Carousel Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#quote-carousel" data-slide-to="0" class="active"><img class="img-responsive "
                                                                                        src="https://s3.amazonaws.com/uifaces/faces/twitter/brad_frost/128.jpg"
                                                                                        alt="">
                </li>
                <li data-target="#quote-carousel" data-slide-to="1"><img class="img-responsive"
                                                                         src="https://s3.amazonaws.com/uifaces/faces/twitter/rssems/128.jpg"
                                                                         alt="">
                </li>
                <li data-target="#quote-carousel" data-slide-to="2"><img class="img-responsive"
                                                                         src="https://s3.amazonaws.com/uifaces/faces/twitter/adellecharles/128.jpg"
                                                                         alt="">
                </li>
            </ol>

            <!-- Carousel Slides / Quotes -->
            <div class="carousel-inner text-center">

                <!-- Quote 1 -->
                <div class="item active">
                    <blockquote>
                        <div class="row">
                            <div class="col-sm-8 col-sm-offset-2">

                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                    nostrud
                                    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                                    irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                                    nulla
                                    pariatur. !</p>
                                <small>Someone famous</small>
                            </div>
                        </div>
                    </blockquote>
                </div>
                <!-- Quote 2 -->
                <div class="item">
                    <blockquote>
                        <div class="row">
                            <div class="col-sm-8 col-sm-offset-2">

                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                    nostrud
                                    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                                    irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                                    nulla
                                    pariatur. </p>
                                <small>Someone famous</small>
                            </div>
                        </div>
                    </blockquote>
                </div>
                <!-- Quote 3 -->
                <div class="item">
                    <blockquote>
                        <div class="row">
                            <div class="col-sm-8 col-sm-offset-2">

                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
                                    nostrud
                                    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute
                                    irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
                                    nulla
                                    pariatur. .</p>
                                <small>Someone famous</small>
                            </div>
                        </div>
                    </blockquote>
                </div>
            </div>

            <!-- Carousel Buttons Next/Prev -->
            <a data-slide="prev" href="#quote-carousel" class="left carousel-control"><i
                    class="fa fa-chevron-left"></i></a>
            <a data-slide="next" href="#quote-carousel" class="right carousel-control"><i
                    class="fa fa-chevron-right"></i></a>
        </div>
    </div>

</section>